// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custommessages.proto
// Protobuf C++ Version: 4.25.9

#ifndef GOOGLE_PROTOBUF_INCLUDED_custommessages_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_custommessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025009 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_custommessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_custommessages_2eproto {
  static const ::uint32_t offsets[];
};
class CMsgGCCustomAuth;
struct CMsgGCCustomAuthDefaultTypeInternal;
extern CMsgGCCustomAuthDefaultTypeInternal _CMsgGCCustomAuth_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum EGCCustomMsg : int {
  k_EMsgGCCustomAuth = 40000,
};

bool EGCCustomMsg_IsValid(int value);
extern const uint32_t EGCCustomMsg_internal_data_[];
constexpr EGCCustomMsg EGCCustomMsg_MIN = static_cast<EGCCustomMsg>(40000);
constexpr EGCCustomMsg EGCCustomMsg_MAX = static_cast<EGCCustomMsg>(40000);
constexpr int EGCCustomMsg_ARRAYSIZE = 40000 + 1;
const std::string& EGCCustomMsg_Name(EGCCustomMsg value);
template <typename T>
const std::string& EGCCustomMsg_Name(T value) {
  static_assert(std::is_same<T, EGCCustomMsg>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EGCCustomMsg_Name().");
  return EGCCustomMsg_Name(static_cast<EGCCustomMsg>(value));
}
const std::string& EGCCustomMsg_Name(EGCCustomMsg value);
bool EGCCustomMsg_Parse(absl::string_view name, EGCCustomMsg* value);

// ===================================================================


// -------------------------------------------------------------------

class CMsgGCCustomAuth final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:CMsgGCCustomAuth) */ {
 public:
  inline CMsgGCCustomAuth() : CMsgGCCustomAuth(nullptr) {}
  ~CMsgGCCustomAuth() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgGCCustomAuth(::google::protobuf::internal::ConstantInitialized);

  inline CMsgGCCustomAuth(const CMsgGCCustomAuth& from)
      : CMsgGCCustomAuth(nullptr, from) {}
  CMsgGCCustomAuth(CMsgGCCustomAuth&& from) noexcept
    : CMsgGCCustomAuth() {
    *this = ::std::move(from);
  }

  inline CMsgGCCustomAuth& operator=(const CMsgGCCustomAuth& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCCustomAuth& operator=(CMsgGCCustomAuth&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const CMsgGCCustomAuth& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgGCCustomAuth* internal_default_instance() {
    return reinterpret_cast<const CMsgGCCustomAuth*>(
               &_CMsgGCCustomAuth_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CMsgGCCustomAuth& a, CMsgGCCustomAuth& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgGCCustomAuth* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCCustomAuth* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgGCCustomAuth* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgGCCustomAuth>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const CMsgGCCustomAuth& from);
  void MergeFrom(const CMsgGCCustomAuth& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CMsgGCCustomAuth* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CMsgGCCustomAuth";
  }
  protected:
  explicit CMsgGCCustomAuth(::google::protobuf::Arena* arena);
  CMsgGCCustomAuth(::google::protobuf::Arena* arena, const CMsgGCCustomAuth& from);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionTicketFieldNumber = 2,
    kSteamIdFieldNumber = 1,
  };
  // optional bytes session_ticket = 2;
  bool has_session_ticket() const;
  void clear_session_ticket() ;
  const std::string& session_ticket() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_session_ticket(Arg_&& arg, Args_... args);
  std::string* mutable_session_ticket();
  PROTOBUF_NODISCARD std::string* release_session_ticket();
  void set_allocated_session_ticket(std::string* value);

  private:
  const std::string& _internal_session_ticket() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_ticket(
      const std::string& value);
  std::string* _internal_mutable_session_ticket();

  public:
  // optional uint64 steam_id = 1;
  bool has_steam_id() const;
  void clear_steam_id() ;
  ::uint64_t steam_id() const;
  void set_steam_id(::uint64_t value);

  private:
  ::uint64_t _internal_steam_id() const;
  void _internal_set_steam_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgGCCustomAuth)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_ticket_;
    ::uint64_t steam_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_custommessages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CMsgGCCustomAuth

// optional uint64 steam_id = 1;
inline bool CMsgGCCustomAuth::has_steam_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CMsgGCCustomAuth::clear_steam_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.steam_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint64_t CMsgGCCustomAuth::steam_id() const {
  // @@protoc_insertion_point(field_get:CMsgGCCustomAuth.steam_id)
  return _internal_steam_id();
}
inline void CMsgGCCustomAuth::set_steam_id(::uint64_t value) {
  _internal_set_steam_id(value);
  // @@protoc_insertion_point(field_set:CMsgGCCustomAuth.steam_id)
}
inline ::uint64_t CMsgGCCustomAuth::_internal_steam_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.steam_id_;
}
inline void CMsgGCCustomAuth::_internal_set_steam_id(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.steam_id_ = value;
}

// optional bytes session_ticket = 2;
inline bool CMsgGCCustomAuth::has_session_ticket() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CMsgGCCustomAuth::clear_session_ticket() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.session_ticket_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CMsgGCCustomAuth::session_ticket() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgGCCustomAuth.session_ticket)
  return _internal_session_ticket();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CMsgGCCustomAuth::set_session_ticket(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.session_ticket_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CMsgGCCustomAuth.session_ticket)
}
inline std::string* CMsgGCCustomAuth::mutable_session_ticket() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_session_ticket();
  // @@protoc_insertion_point(field_mutable:CMsgGCCustomAuth.session_ticket)
  return _s;
}
inline const std::string& CMsgGCCustomAuth::_internal_session_ticket() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.session_ticket_.Get();
}
inline void CMsgGCCustomAuth::_internal_set_session_ticket(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.session_ticket_.Set(value, GetArena());
}
inline std::string* CMsgGCCustomAuth::_internal_mutable_session_ticket() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.session_ticket_.Mutable( GetArena());
}
inline std::string* CMsgGCCustomAuth::release_session_ticket() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CMsgGCCustomAuth.session_ticket)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.session_ticket_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.session_ticket_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void CMsgGCCustomAuth::set_allocated_session_ticket(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.session_ticket_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.session_ticket_.IsDefault()) {
          _impl_.session_ticket_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CMsgGCCustomAuth.session_ticket)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EGCCustomMsg> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_custommessages_2eproto_2epb_2eh
