// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custommessages.proto

#include "custommessages.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CMsgGCCustomAuth::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        session_ticket_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        steam_id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR CMsgGCCustomAuth::CMsgGCCustomAuth(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CMsgGCCustomAuthDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGCCustomAuthDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCCustomAuthDefaultTypeInternal() {}
  union {
    CMsgGCCustomAuth _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCCustomAuthDefaultTypeInternal _CMsgGCCustomAuth_default_instance_;
PROTOBUF_CONSTINIT const uint32_t EGCCustomMsg_internal_data_[] = {
    0u, 65536u, 40000u, };
bool EGCCustomMsg_IsValid(int value) {
  return 40000 <= value && value <= 40000;
}
static ::google::protobuf::internal::ExplicitlyConstructed<std::string>
    EGCCustomMsg_strings[1] = {};

static const char EGCCustomMsg_names[] = {
    "k_EMsgGCCustomAuth"
};

static const ::google::protobuf::internal::EnumEntry EGCCustomMsg_entries[] =
    {
        {{&EGCCustomMsg_names[0], 18}, 40000},
};

static const int EGCCustomMsg_entries_by_number[] = {
    0,  // 40000 -> k_EMsgGCCustomAuth
};

const std::string& EGCCustomMsg_Name(EGCCustomMsg value) {
  static const bool kDummy =
      ::google::protobuf::internal::InitializeEnumStrings(
          EGCCustomMsg_entries, EGCCustomMsg_entries_by_number,
          1, EGCCustomMsg_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(
      EGCCustomMsg_entries, EGCCustomMsg_entries_by_number, 1,
      value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString()
                   : EGCCustomMsg_strings[idx].get();
}

bool EGCCustomMsg_Parse(absl::string_view name, EGCCustomMsg* value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EGCCustomMsg_entries, 1, name, &int_value);
  if (success) {
    *value = static_cast<EGCCustomMsg>(int_value);
  }
  return success;
}
// ===================================================================

class CMsgGCCustomAuth::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgGCCustomAuth>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_._has_bits_);
  static void set_has_steam_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_session_ticket(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CMsgGCCustomAuth::CMsgGCCustomAuth(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGCCustomAuth)
}
inline PROTOBUF_NDEBUG_INLINE CMsgGCCustomAuth::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        session_ticket_(arena, from.session_ticket_) {}

CMsgGCCustomAuth::CMsgGCCustomAuth(
    ::google::protobuf::Arena* arena,
    const CMsgGCCustomAuth& from)
    : ::google::protobuf::MessageLite(arena) {
  CMsgGCCustomAuth* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.steam_id_ = from._impl_.steam_id_;

  // @@protoc_insertion_point(copy_constructor:CMsgGCCustomAuth)
}
inline PROTOBUF_NDEBUG_INLINE CMsgGCCustomAuth::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        session_ticket_(arena) {}

inline void CMsgGCCustomAuth::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.steam_id_ = {};
}
CMsgGCCustomAuth::~CMsgGCCustomAuth() {
  // @@protoc_insertion_point(destructor:CMsgGCCustomAuth)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void CMsgGCCustomAuth::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.session_ticket_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CMsgGCCustomAuth::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCCustomAuth)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.session_ticket_.ClearNonDefaultToEmpty();
  }
  _impl_.steam_id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* CMsgGCCustomAuth::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> CMsgGCCustomAuth::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CMsgGCCustomAuth_default_instance_._instance,
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
  }, {{
    // optional bytes session_ticket = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.session_ticket_)}},
    // optional uint64 steam_id = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.steam_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 steam_id = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.steam_id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional bytes session_ticket = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.session_ticket_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CMsgGCCustomAuth::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCCustomAuth)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 steam_id = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_steam_id(), target);
  }

  // optional bytes session_ticket = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_session_ticket();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCCustomAuth)
  return target;
}

::size_t CMsgGCCustomAuth::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGCCustomAuth)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional bytes session_ticket = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_session_ticket());
    }

    // optional uint64 steam_id = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_steam_id());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CMsgGCCustomAuth::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const CMsgGCCustomAuth*>(
      &from));
}

void CMsgGCCustomAuth::MergeFrom(const CMsgGCCustomAuth& from) {
  CMsgGCCustomAuth* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCCustomAuth)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_session_ticket(from._internal_session_ticket());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.steam_id_ = from._impl_.steam_id_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void CMsgGCCustomAuth::CopyFrom(const CMsgGCCustomAuth& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCCustomAuth)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CMsgGCCustomAuth::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CMsgGCCustomAuth::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CMsgGCCustomAuth::InternalSwap(CMsgGCCustomAuth* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.session_ticket_, &other->_impl_.session_ticket_, arena);
        swap(_impl_.steam_id_, other->_impl_.steam_id_);
}

std::string CMsgGCCustomAuth::GetTypeName() const {
  return "CMsgGCCustomAuth";
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
