// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: custommessages.proto
// Protobuf C++ Version: 7.34.1

#ifndef custommessages_2eproto_2epb_2eh
#define custommessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_custommessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_custommessages_2eproto {
  static const ::uint32_t offsets[];
};
enum EGCCustomMsg : int;
extern const uint32_t EGCCustomMsg_internal_data_[];
class CMsgGCCustomAuth;
struct CMsgGCCustomAuthDefaultTypeInternal;
extern CMsgGCCustomAuthDefaultTypeInternal _CMsgGCCustomAuth_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<17> CMsgGCCustomAuth_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EGCCustomMsg_internal_data_>
    internal::EnumTraitsImpl::value<::EGCCustomMsg>;
}  // namespace protobuf
}  // namespace google

enum EGCCustomMsg : int {
  k_EMsgGCCustomAuth = 40000,
};

extern const uint32_t EGCCustomMsg_internal_data_[];
inline constexpr EGCCustomMsg EGCCustomMsg_MIN =
    static_cast<EGCCustomMsg>(40000);
inline constexpr EGCCustomMsg EGCCustomMsg_MAX =
    static_cast<EGCCustomMsg>(40000);
[[nodiscard]] inline bool EGCCustomMsg_IsValid(int value) {
  return 40000 <= value && value <= 40000;
}
inline constexpr int EGCCustomMsg_ARRAYSIZE = 40000 + 1;
[[nodiscard]] const ::std::string& EGCCustomMsg_Name(EGCCustomMsg value);
template <typename T>
[[nodiscard]] const ::std::string& EGCCustomMsg_Name(T value) {
  static_assert(::std::is_same<T, EGCCustomMsg>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EGCCustomMsg_Name().");
  return EGCCustomMsg_Name(static_cast<EGCCustomMsg>(value));
}
[[nodiscard]] bool EGCCustomMsg_Parse(
    ::absl::string_view name, EGCCustomMsg* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CMsgGCCustomAuth final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:CMsgGCCustomAuth) */ {
 public:
  inline CMsgGCCustomAuth() : CMsgGCCustomAuth(nullptr) {}
  ~CMsgGCCustomAuth() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgGCCustomAuth* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgGCCustomAuth));
  }
#endif

  template <typename = void>
  explicit constexpr CMsgGCCustomAuth(::google::protobuf::internal::ConstantInitialized);

  inline CMsgGCCustomAuth(const CMsgGCCustomAuth& from) : CMsgGCCustomAuth(nullptr, from) {}
  inline CMsgGCCustomAuth(CMsgGCCustomAuth&& from) noexcept
      : CMsgGCCustomAuth(nullptr, ::std::move(from)) {}
  inline CMsgGCCustomAuth& operator=(const CMsgGCCustomAuth& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCCustomAuth& operator=(CMsgGCCustomAuth&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const CMsgGCCustomAuth& default_instance() {
    return *reinterpret_cast<const CMsgGCCustomAuth*>(
        &_CMsgGCCustomAuth_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CMsgGCCustomAuth& a, CMsgGCCustomAuth& b) { a.Swap(&b); }
  inline void Swap(CMsgGCCustomAuth* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCCustomAuth* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CMsgGCCustomAuth* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<CMsgGCCustomAuth>(arena);
  }
  void CopyFrom(const CMsgGCCustomAuth& from);
  void MergeFrom(const CMsgGCCustomAuth& from) { CMsgGCCustomAuth::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgGCCustomAuth* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgGCCustomAuth"; }

  explicit CMsgGCCustomAuth(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgGCCustomAuth(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgGCCustomAuth& from);
  CMsgGCCustomAuth(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgGCCustomAuth&& from) noexcept
      : CMsgGCCustomAuth(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionTicketFieldNumber = 2,
    kSteamIdFieldNumber = 1,
  };
  // optional bytes session_ticket = 2;
  [[nodiscard]] bool has_session_ticket()
      const;
  void clear_session_ticket() ;
  [[nodiscard]] const ::std::string& session_ticket() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_ticket(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_ticket();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_ticket();
  void set_allocated_session_ticket(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_ticket() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_ticket(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_ticket();

  public:
  // optional uint64 steam_id = 1;
  [[nodiscard]] bool has_steam_id()
      const;
  void clear_steam_id() ;
  [[nodiscard]] ::uint64_t steam_id() const;
  void set_steam_id(::uint64_t value);

  private:
  ::uint64_t _internal_steam_id() const;
  void _internal_set_steam_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgGCCustomAuth)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgGCCustomAuth& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_ticket_;
    ::uint64_t steam_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_custommessages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<17> CMsgGCCustomAuth_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CMsgGCCustomAuth

// optional uint64 steam_id = 1;
inline bool CMsgGCCustomAuth::has_steam_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgGCCustomAuth::clear_steam_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steam_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t CMsgGCCustomAuth::steam_id() const {
  // @@protoc_insertion_point(field_get:CMsgGCCustomAuth.steam_id)
  return _internal_steam_id();
}
inline void CMsgGCCustomAuth::set_steam_id(::uint64_t value) {
  _internal_set_steam_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgGCCustomAuth.steam_id)
}
inline ::uint64_t CMsgGCCustomAuth::_internal_steam_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.steam_id_;
}
inline void CMsgGCCustomAuth::_internal_set_steam_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steam_id_ = value;
}

// optional bytes session_ticket = 2;
inline bool CMsgGCCustomAuth::has_session_ticket() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgGCCustomAuth::clear_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_ticket_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CMsgGCCustomAuth::session_ticket() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgGCCustomAuth.session_ticket)
  return _internal_session_ticket();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CMsgGCCustomAuth::set_session_ticket(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_ticket_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CMsgGCCustomAuth.session_ticket)
}
inline ::std::string* PROTOBUF_NONNULL CMsgGCCustomAuth::mutable_session_ticket()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_ticket();
  // @@protoc_insertion_point(field_mutable:CMsgGCCustomAuth.session_ticket)
  return _s;
}
inline const ::std::string& CMsgGCCustomAuth::_internal_session_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_ticket_.Get();
}
inline void CMsgGCCustomAuth::_internal_set_session_ticket(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_ticket_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CMsgGCCustomAuth::_internal_mutable_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_ticket_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CMsgGCCustomAuth::release_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CMsgGCCustomAuth.session_ticket)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_ticket_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_ticket_.Set("", GetArena());
  }
  return released;
}
inline void CMsgGCCustomAuth::set_allocated_session_ticket(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_ticket_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_ticket_.IsDefault()) {
    _impl_.session_ticket_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgGCCustomAuth.session_ticket)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EGCCustomMsg> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // custommessages_2eproto_2epb_2eh
