// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: custommessages.proto
// Protobuf C++ Version: 7.34.1

#include "custommessages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CMsgGCCustomAuth::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        session_ticket_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        steam_id_{::uint64_t{0u}} {}

template <typename>
constexpr CMsgGCCustomAuth::CMsgGCCustomAuth(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(CMsgGCCustomAuth_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CMsgGCCustomAuthDefaultTypeInternal {
  constexpr CMsgGCCustomAuthDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCCustomAuthDefaultTypeInternal() {}
  union {
    CMsgGCCustomAuth _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCCustomAuthDefaultTypeInternal _CMsgGCCustomAuth_default_instance_;
PROTOBUF_CONSTINIT const uint32_t EGCCustomMsg_internal_data_[] = {
    0u, 65536u, 40000u, };
static const char EGCCustomMsg_names[] = {
    "k_EMsgGCCustomAuth"
};

static const ::google::protobuf::internal::EnumEntry EGCCustomMsg_entries[] = {
    {{&EGCCustomMsg_names[0], 18}, 40000},
};

static const int EGCCustomMsg_entries_by_number[] = {
    0,  // 40000 -> k_EMsgGCCustomAuth
};

[[nodiscard]] bool EGCCustomMsg_Parse(::absl::string_view name,
                                  EGCCustomMsg* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EGCCustomMsg_entries, 1, name, &int_value);
  if (success) {
    *value = static_cast<EGCCustomMsg>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    EGCCustomMsg_strings[1] = {};

[[nodiscard]] const ::std::string& EGCCustomMsg_Name(EGCCustomMsg value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      EGCCustomMsg_entries, EGCCustomMsg_entries_by_number, 1,
      EGCCustomMsg_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(EGCCustomMsg_entries,
                                  EGCCustomMsg_entries_by_number,
                                  1, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : EGCCustomMsg_strings[idx].get();
}
// ===================================================================

class CMsgGCCustomAuth::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CMsgGCCustomAuth>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_._has_bits_);
};

CMsgGCCustomAuth::CMsgGCCustomAuth(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCCustomAuth_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGCCustomAuth)
}
PROTOBUF_NDEBUG_INLINE CMsgGCCustomAuth::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CMsgGCCustomAuth& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        session_ticket_(arena, from.session_ticket_) {}

CMsgGCCustomAuth::CMsgGCCustomAuth(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CMsgGCCustomAuth& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCCustomAuth_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CMsgGCCustomAuth* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.steam_id_ = from._impl_.steam_id_;

  // @@protoc_insertion_point(copy_constructor:CMsgGCCustomAuth)
}
PROTOBUF_NDEBUG_INLINE CMsgGCCustomAuth::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        session_ticket_(arena) {}

inline void CMsgGCCustomAuth::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.steam_id_ = {};
}
CMsgGCCustomAuth::~CMsgGCCustomAuth() {
  // @@protoc_insertion_point(destructor:CMsgGCCustomAuth)
  SharedDtor(*this);
}
inline void CMsgGCCustomAuth::SharedDtor(MessageLite& self) {
  CMsgGCCustomAuth& this_ = static_cast<CMsgGCCustomAuth&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.session_ticket_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CMsgGCCustomAuth::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CMsgGCCustomAuth(arena);
}
constexpr auto CMsgGCCustomAuth::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CMsgGCCustomAuth),
                                            alignof(CMsgGCCustomAuth));
}
constexpr auto CMsgGCCustomAuth::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<17>{
      {
          &_CMsgGCCustomAuth_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CMsgGCCustomAuth::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<CMsgGCCustomAuth>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CMsgGCCustomAuth::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<CMsgGCCustomAuth>(), &CMsgGCCustomAuth::ByteSizeLong,
              &CMsgGCCustomAuth::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_._cached_size_),
          true,
      },
      "CMsgGCCustomAuth",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<17> CMsgGCCustomAuth_class_data_ =
    CMsgGCCustomAuth::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CMsgGCCustomAuth::GetClassData() const {
  return CMsgGCCustomAuth_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
CMsgGCCustomAuth::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CMsgGCCustomAuth_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgGCCustomAuth>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes session_ticket = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.session_ticket_)}},
    // optional uint64 steam_id = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.steam_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 steam_id = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.steam_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional bytes session_ticket = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgGCCustomAuth, _impl_.session_ticket_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CMsgGCCustomAuth::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCCustomAuth)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.session_ticket_.ClearNonDefaultToEmpty();
  }
  _impl_.steam_id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CMsgGCCustomAuth::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CMsgGCCustomAuth& this_ = static_cast<const CMsgGCCustomAuth&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CMsgGCCustomAuth::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CMsgGCCustomAuth& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCCustomAuth)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 steam_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_steam_id(), target);
  }

  // optional bytes session_ticket = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_session_ticket();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCCustomAuth)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CMsgGCCustomAuth::ByteSizeLong(const MessageLite& base) {
  const CMsgGCCustomAuth& this_ = static_cast<const CMsgGCCustomAuth&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CMsgGCCustomAuth::ByteSizeLong() const {
  const CMsgGCCustomAuth& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CMsgGCCustomAuth)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional bytes session_ticket = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_session_ticket());
    }
    // optional uint64 steam_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_steam_id());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CMsgGCCustomAuth::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CMsgGCCustomAuth*>(&to_msg);
  auto& from = static_cast<const CMsgGCCustomAuth&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCCustomAuth)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_session_ticket(from._internal_session_ticket());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.steam_id_ = from._impl_.steam_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void CMsgGCCustomAuth::CopyFrom(const CMsgGCCustomAuth& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCCustomAuth)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgGCCustomAuth::InternalSwap(CMsgGCCustomAuth* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.session_ticket_, &other->_impl_.session_ticket_, arena);
  swap(_impl_.steam_id_, other->_impl_.steam_id_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
