// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: econ_gcmessages.proto
// Protobuf C++ Version: 7.34.1

#include "econ_gcmessages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CMsgGCUserTrackTimePlayedConsecutively::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        state_{0u} {}

template <typename>
constexpr CMsgGCUserTrackTimePlayedConsecutively::CMsgGCUserTrackTimePlayedConsecutively(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(CMsgGCUserTrackTimePlayedConsecutively_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal {
  constexpr CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal() {}
  union {
    CMsgGCUserTrackTimePlayedConsecutively _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal _CMsgGCUserTrackTimePlayedConsecutively_default_instance_;

inline constexpr CMsgGCItemCustomizationNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        item_id_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::CMsgGCItemCustomizationNotification,
            PROTOBUF_FIELD_OFFSET(::CMsgGCItemCustomizationNotification, _impl_.item_id_)>()
        }
        #else
        item_id_ {}
        #endif
        ,
        request_{0u} {}

template <typename>
constexpr CMsgGCItemCustomizationNotification::CMsgGCItemCustomizationNotification(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(CMsgGCItemCustomizationNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CMsgGCItemCustomizationNotificationDefaultTypeInternal {
  constexpr CMsgGCItemCustomizationNotificationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCItemCustomizationNotificationDefaultTypeInternal() {}
  union {
    CMsgGCItemCustomizationNotification _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCItemCustomizationNotificationDefaultTypeInternal _CMsgGCItemCustomizationNotification_default_instance_;

inline constexpr CMsgGCGiftedItems::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        recipients_accountids_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::CMsgGCGiftedItems,
            PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.recipients_accountids_)>()
        }
        #else
        recipients_accountids_ {}
        #endif
        ,
        accountid_{0u},
        giftdefindex_{0u},
        max_gifts_possible_{0u},
        num_eligible_recipients_{0u} {}

template <typename>
constexpr CMsgGCGiftedItems::CMsgGCGiftedItems(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(CMsgGCGiftedItems_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CMsgGCGiftedItemsDefaultTypeInternal {
  constexpr CMsgGCGiftedItemsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGCGiftedItemsDefaultTypeInternal() {}
  union {
    CMsgGCGiftedItems _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGCGiftedItemsDefaultTypeInternal _CMsgGCGiftedItems_default_instance_;

inline constexpr CMsgCasketItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        casket_item_id_{::uint64_t{0u}},
        item_item_id_{::uint64_t{0u}} {}

template <typename>
constexpr CMsgCasketItem::CMsgCasketItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(CMsgCasketItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CMsgCasketItemDefaultTypeInternal {
  constexpr CMsgCasketItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgCasketItemDefaultTypeInternal() {}
  union {
    CMsgCasketItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgCasketItemDefaultTypeInternal _CMsgCasketItem_default_instance_;
PROTOBUF_CONSTINIT const uint32_t EGCItemMsg_internal_data_[] = {
    1836008u, 1504u, 4289200124u, 4294967142u, 7u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 4278190080u, 63u, 0u, 1610612736u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 57344u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 4286578687u, };
static const char EGCItemMsg_names[] = {
    "k_EMsgGCAddItemToSocketResponse_DEPRECATED"
    "k_EMsgGCAddItemToSocket_DEPRECATED"
    "k_EMsgGCAddSocketToBaseItem_DEPRECATED"
    "k_EMsgGCAddSocketToItemResponse_DEPRECATED"
    "k_EMsgGCAddSocketToItem_DEPRECATED"
    "k_EMsgGCAdjustEquipSlots"
    "k_EMsgGCAdjustItemEquippedState"
    "k_EMsgGCAdjustItemEquippedStateMulti"
    "k_EMsgGCApplyConsumableEffects"
    "k_EMsgGCApplyEggEssence"
    "k_EMsgGCApplyPennantUpgrade"
    "k_EMsgGCApplySticker"
    "k_EMsgGCApplyStrangePart"
    "k_EMsgGCBackpackSortFinished"
    "k_EMsgGCBannedWordListRequest"
    "k_EMsgGCBannedWordListResponse"
    "k_EMsgGCBase"
    "k_EMsgGCCasketItemAdd"
    "k_EMsgGCCasketItemExtract"
    "k_EMsgGCCasketItemLoadContents"
    "k_EMsgGCClientDisplayNotification"
    "k_EMsgGCClientVersionUpdated"
    "k_EMsgGCCollectItem"
    "k_EMsgGCConsumableExhausted"
    "k_EMsgGCCraft"
    "k_EMsgGCCraftResponse"
    "k_EMsgGCCustomizeItemTexture"
    "k_EMsgGCCustomizeItemTextureResponse"
    "k_EMsgGCDelete"
    "k_EMsgGCDeliverGift"
    "k_EMsgGCDeliverGiftResponseGiver"
    "k_EMsgGCDeliverGiftResponseReceiver"
    "k_EMsgGCDev_NewItemRequest"
    "k_EMsgGCDev_NewItemRequestResponse"
    "k_EMsgGCDev_PaintKitDropItem"
    "k_EMsgGCGiftWrapItem"
    "k_EMsgGCGiftWrapItemResponse"
    "k_EMsgGCGiftedItems"
    "k_EMsgGCGiftedItems_DEPRECATED"
    "k_EMsgGCGoldenWrenchBroadcast"
    "k_EMsgGCItemAcknowledged"
    "k_EMsgGCItemAcknowledged__DEPRECATED"
    "k_EMsgGCItemCustomizationNotification"
    "k_EMsgGCItemPreviewCheckStatus"
    "k_EMsgGCItemPreviewExpire"
    "k_EMsgGCItemPreviewExpireNotification"
    "k_EMsgGCItemPreviewItemBoughtNotification"
    "k_EMsgGCItemPreviewRequest"
    "k_EMsgGCItemPreviewRequestResponse"
    "k_EMsgGCItemPreviewStatusResponse"
    "k_EMsgGCLookupAccount"
    "k_EMsgGCLookupAccountName"
    "k_EMsgGCLookupAccountNameResponse"
    "k_EMsgGCLookupAccountResponse"
    "k_EMsgGCMOTDRequest"
    "k_EMsgGCMOTDRequestResponse"
    "k_EMsgGCModifyItemAttribute"
    "k_EMsgGCNameBaseItem"
    "k_EMsgGCNameBaseItemResponse"
    "k_EMsgGCNameEggEssenceResponse"
    "k_EMsgGCNameItem"
    "k_EMsgGCNameItemNotification"
    "k_EMsgGCPaintItem"
    "k_EMsgGCPaintItemResponse"
    "k_EMsgGCPaintKitBaseItem"
    "k_EMsgGCPaintKitItem"
    "k_EMsgGCPaintKitItemResponse"
    "k_EMsgGCRecurringSubscriptionStatus"
    "k_EMsgGCRemoveCustomTexture"
    "k_EMsgGCRemoveCustomTextureResponse"
    "k_EMsgGCRemoveItemName"
    "k_EMsgGCRemoveItemPaint"
    "k_EMsgGCRemoveMakersMark"
    "k_EMsgGCRemoveMakersMarkResponse"
    "k_EMsgGCRemoveSocketItemResponse_DEPRECATED"
    "k_EMsgGCRemoveSocketItem_DEPRECATED"
    "k_EMsgGCRemoveUniqueCraftIndex"
    "k_EMsgGCRemoveUniqueCraftIndexResponse"
    "k_EMsgGCRequestAnnouncements"
    "k_EMsgGCRequestAnnouncementsResponse"
    "k_EMsgGCRequestPassportItemGrant"
    "k_EMsgGCSaxxyBroadcast"
    "k_EMsgGCServerBrowser_BlacklistServer"
    "k_EMsgGCServerBrowser_FavoriteServer"
    "k_EMsgGCServerRentalsBase"
    "k_EMsgGCServerVersionUpdated"
    "k_EMsgGCSetItemPosition"
    "k_EMsgGCSetItemPositions"
    "k_EMsgGCSetItemStyle"
    "k_EMsgGCShowItemsPickedUp"
    "k_EMsgGCSortItems"
    "k_EMsgGCStatTrakSwap"
    "k_EMsgGCStoreGetUserData"
    "k_EMsgGCStoreGetUserDataResponse"
    "k_EMsgGCStorePurchaseCancel"
    "k_EMsgGCStorePurchaseCancelResponse"
    "k_EMsgGCStorePurchaseFinalize"
    "k_EMsgGCStorePurchaseFinalizeResponse"
    "k_EMsgGCStorePurchaseInit"
    "k_EMsgGCStorePurchaseInitResponse"
    "k_EMsgGCStorePurchaseInitResponse_DEPRECATED"
    "k_EMsgGCStorePurchaseInit_DEPRECATED"
    "k_EMsgGCStorePurchaseQueryTxn"
    "k_EMsgGCStorePurchaseQueryTxnResponse"
    "k_EMsgGCToGCBannedWordListBroadcast"
    "k_EMsgGCToGCBannedWordListUpdated"
    "k_EMsgGCToGCBroadcastConsoleCommand"
    "k_EMsgGCToGCDirtyMultipleSDOCache"
    "k_EMsgGCToGCDirtySDOCache"
    "k_EMsgGCToGCIsTrustedServer"
    "k_EMsgGCToGCIsTrustedServerResponse"
    "k_EMsgGCToGCUpdateSQLKeyValue"
    "k_EMsgGCToGCWebAPIAccountChanged"
    "k_EMsgGCTradingBase"
    "k_EMsgGCTrading_CancelSession"
    "k_EMsgGCTrading_ConfirmOffer"
    "k_EMsgGCTrading_InitiateTradeRequest"
    "k_EMsgGCTrading_InitiateTradeResponse"
    "k_EMsgGCTrading_ReadinessResponse"
    "k_EMsgGCTrading_RemoveItem"
    "k_EMsgGCTrading_SessionClosed"
    "k_EMsgGCTrading_SetItem"
    "k_EMsgGCTrading_SetReadiness"
    "k_EMsgGCTrading_StartSession"
    "k_EMsgGCTrading_TradeChatMsg"
    "k_EMsgGCTrading_TradeTypingChatMsg"
    "k_EMsgGCTrading_UpdateTradeInfo"
    "k_EMsgGCUnlockCrate"
    "k_EMsgGCUnlockCrateResponse"
    "k_EMsgGCUnlockItemStyle"
    "k_EMsgGCUnlockItemStyleResponse"
    "k_EMsgGCUnwrapGiftRequest"
    "k_EMsgGCUnwrapGiftResponse"
    "k_EMsgGCUpdateItemSchema"
    "k_EMsgGCUseItemRequest"
    "k_EMsgGCUseItemResponse"
    "k_EMsgGCUsedClaimCodeItem"
    "k_EMsgGCUserTrackTimePlayedConsecutively"
    "k_EMsgGCVerifyCacheSubscription"
    "k_EMsgGC_IncrementKillCountAttribute"
    "k_EMsgGC_IncrementKillCountResponse"
    "k_EMsgGC_ReportAbuse"
    "k_EMsgGC_ReportAbuseResponse"
    "k_EMsgGC_RevolvingLootList_DEPRECATED"
};

static const ::google::protobuf::internal::EnumEntry EGCItemMsg_entries[] = {
    {{&EGCItemMsg_names[0], 42}, 1015},
    {{&EGCItemMsg_names[42], 34}, 1014},
    {{&EGCItemMsg_names[76], 38}, 1016},
    {{&EGCItemMsg_names[114], 42}, 1018},
    {{&EGCItemMsg_names[156], 34}, 1017},
    {{&EGCItemMsg_names[190], 24}, 2531},
    {{&EGCItemMsg_names[214], 31}, 1059},
    {{&EGCItemMsg_names[245], 36}, 2529},
    {{&EGCItemMsg_names[281], 30}, 1069},
    {{&EGCItemMsg_names[311], 23}, 1078},
    {{&EGCItemMsg_names[334], 27}, 1076},
    {{&EGCItemMsg_names[361], 20}, 1086},
    {{&EGCItemMsg_names[381], 24}, 1073},
    {{&EGCItemMsg_names[405], 28}, 1058},
    {{&EGCItemMsg_names[433], 29}, 2512},
    {{&EGCItemMsg_names[462], 30}, 2513},
    {{&EGCItemMsg_names[492], 12}, 1000},
    {{&EGCItemMsg_names[504], 21}, 1092},
    {{&EGCItemMsg_names[525], 25}, 1093},
    {{&EGCItemMsg_names[550], 30}, 1094},
    {{&EGCItemMsg_names[580], 33}, 1072},
    {{&EGCItemMsg_names[613], 28}, 2528},
    {{&EGCItemMsg_names[641], 19}, 1061},
    {{&EGCItemMsg_names[660], 27}, 1070},
    {{&EGCItemMsg_names[687], 13}, 1002},
    {{&EGCItemMsg_names[700], 21}, 1003},
    {{&EGCItemMsg_names[721], 28}, 1023},
    {{&EGCItemMsg_names[749], 36}, 1024},
    {{&EGCItemMsg_names[785], 14}, 1004},
    {{&EGCItemMsg_names[799], 19}, 1034},
    {{&EGCItemMsg_names[818], 32}, 1035},
    {{&EGCItemMsg_names[850], 35}, 1036},
    {{&EGCItemMsg_names[885], 26}, 2001},
    {{&EGCItemMsg_names[911], 34}, 2002},
    {{&EGCItemMsg_names[945], 28}, 2003},
    {{&EGCItemMsg_names[973], 20}, 1032},
    {{&EGCItemMsg_names[993], 28}, 1033},
    {{&EGCItemMsg_names[1021], 19}, 1083},
    {{&EGCItemMsg_names[1040], 30}, 1027},
    {{&EGCItemMsg_names[1070], 29}, 1011},
    {{&EGCItemMsg_names[1099], 24}, 1087},
    {{&EGCItemMsg_names[1123], 36}, 1062},
    {{&EGCItemMsg_names[1159], 37}, 1090},
    {{&EGCItemMsg_names[1196], 30}, 1701},
    {{&EGCItemMsg_names[1226], 25}, 1705},
    {{&EGCItemMsg_names[1251], 37}, 1706},
    {{&EGCItemMsg_names[1288], 41}, 1707},
    {{&EGCItemMsg_names[1329], 26}, 1703},
    {{&EGCItemMsg_names[1355], 34}, 1704},
    {{&EGCItemMsg_names[1389], 33}, 1702},
    {{&EGCItemMsg_names[1422], 21}, 1043},
    {{&EGCItemMsg_names[1443], 25}, 1045},
    {{&EGCItemMsg_names[1468], 33}, 1046},
    {{&EGCItemMsg_names[1501], 29}, 1044},
    {{&EGCItemMsg_names[1530], 19}, 1012},
    {{&EGCItemMsg_names[1549], 27}, 1013},
    {{&EGCItemMsg_names[1576], 27}, 1091},
    {{&EGCItemMsg_names[1603], 20}, 1019},
    {{&EGCItemMsg_names[1623], 28}, 1020},
    {{&EGCItemMsg_names[1651], 30}, 1079},
    {{&EGCItemMsg_names[1681], 16}, 1006},
    {{&EGCItemMsg_names[1697], 28}, 1068},
    {{&EGCItemMsg_names[1725], 17}, 1009},
    {{&EGCItemMsg_names[1742], 25}, 1010},
    {{&EGCItemMsg_names[1767], 24}, 1081},
    {{&EGCItemMsg_names[1791], 20}, 1080},
    {{&EGCItemMsg_names[1811], 28}, 1082},
    {{&EGCItemMsg_names[1839], 35}, 2530},
    {{&EGCItemMsg_names[1874], 27}, 1051},
    {{&EGCItemMsg_names[1901], 35}, 1052},
    {{&EGCItemMsg_names[1936], 22}, 1030},
    {{&EGCItemMsg_names[1958], 23}, 1031},
    {{&EGCItemMsg_names[1981], 24}, 1053},
    {{&EGCItemMsg_names[2005], 32}, 1054},
    {{&EGCItemMsg_names[2037], 43}, 1022},
    {{&EGCItemMsg_names[2080], 35}, 1021},
    {{&EGCItemMsg_names[2115], 30}, 1055},
    {{&EGCItemMsg_names[2145], 38}, 1056},
    {{&EGCItemMsg_names[2183], 28}, 2525},
    {{&EGCItemMsg_names[2211], 36}, 2526},
    {{&EGCItemMsg_names[2247], 32}, 2527},
    {{&EGCItemMsg_names[2279], 22}, 1057},
    {{&EGCItemMsg_names[2301], 37}, 1602},
    {{&EGCItemMsg_names[2338], 36}, 1601},
    {{&EGCItemMsg_names[2374], 25}, 1700},
    {{&EGCItemMsg_names[2399], 28}, 2522},
    {{&EGCItemMsg_names[2427], 23}, 1001},
    {{&EGCItemMsg_names[2450], 24}, 1077},
    {{&EGCItemMsg_names[2474], 20}, 1039},
    {{&EGCItemMsg_names[2494], 25}, 1071},
    {{&EGCItemMsg_names[2519], 17}, 1041},
    {{&EGCItemMsg_names[2536], 20}, 1088},
    {{&EGCItemMsg_names[2556], 24}, 2500},
    {{&EGCItemMsg_names[2580], 32}, 2501},
    {{&EGCItemMsg_names[2612], 27}, 2506},
    {{&EGCItemMsg_names[2639], 35}, 2507},
    {{&EGCItemMsg_names[2674], 29}, 2504},
    {{&EGCItemMsg_names[2703], 37}, 2505},
    {{&EGCItemMsg_names[2740], 25}, 2510},
    {{&EGCItemMsg_names[2765], 33}, 2511},
    {{&EGCItemMsg_names[2798], 44}, 2503},
    {{&EGCItemMsg_names[2842], 36}, 2502},
    {{&EGCItemMsg_names[2878], 29}, 2508},
    {{&EGCItemMsg_names[2907], 37}, 2509},
    {{&EGCItemMsg_names[2944], 35}, 2514},
    {{&EGCItemMsg_names[2979], 33}, 2515},
    {{&EGCItemMsg_names[3012], 35}, 2521},
    {{&EGCItemMsg_names[3047], 33}, 2517},
    {{&EGCItemMsg_names[3080], 25}, 2516},
    {{&EGCItemMsg_names[3105], 27}, 2519},
    {{&EGCItemMsg_names[3132], 35}, 2520},
    {{&EGCItemMsg_names[3167], 29}, 2518},
    {{&EGCItemMsg_names[3196], 32}, 2524},
    {{&EGCItemMsg_names[3228], 19}, 1500},
    {{&EGCItemMsg_names[3247], 29}, 1510},
    {{&EGCItemMsg_names[3276], 28}, 1512},
    {{&EGCItemMsg_names[3304], 36}, 1501},
    {{&EGCItemMsg_names[3340], 37}, 1502},
    {{&EGCItemMsg_names[3377], 33}, 1508},
    {{&EGCItemMsg_names[3410], 26}, 1505},
    {{&EGCItemMsg_names[3436], 29}, 1509},
    {{&EGCItemMsg_names[3465], 23}, 1504},
    {{&EGCItemMsg_names[3488], 28}, 1507},
    {{&EGCItemMsg_names[3516], 28}, 1503},
    {{&EGCItemMsg_names[3544], 28}, 1511},
    {{&EGCItemMsg_names[3572], 34}, 1513},
    {{&EGCItemMsg_names[3606], 31}, 1506},
    {{&EGCItemMsg_names[3637], 19}, 1007},
    {{&EGCItemMsg_names[3656], 27}, 1008},
    {{&EGCItemMsg_names[3683], 23}, 1084},
    {{&EGCItemMsg_names[3706], 31}, 1085},
    {{&EGCItemMsg_names[3737], 25}, 1037},
    {{&EGCItemMsg_names[3762], 26}, 1038},
    {{&EGCItemMsg_names[3788], 24}, 1049},
    {{&EGCItemMsg_names[3812], 22}, 1025},
    {{&EGCItemMsg_names[3834], 23}, 1026},
    {{&EGCItemMsg_names[3857], 25}, 1040},
    {{&EGCItemMsg_names[3882], 40}, 1089},
    {{&EGCItemMsg_names[3922], 31}, 1005},
    {{&EGCItemMsg_names[3953], 36}, 1074},
    {{&EGCItemMsg_names[3989], 35}, 1075},
    {{&EGCItemMsg_names[4024], 20}, 1065},
    {{&EGCItemMsg_names[4044], 28}, 1066},
    {{&EGCItemMsg_names[4072], 37}, 1042},
};

static const int EGCItemMsg_entries_by_number[] = {
    16,  // 1000 -> k_EMsgGCBase
    86,  // 1001 -> k_EMsgGCSetItemPosition
    24,  // 1002 -> k_EMsgGCCraft
    25,  // 1003 -> k_EMsgGCCraftResponse
    28,  // 1004 -> k_EMsgGCDelete
    138,  // 1005 -> k_EMsgGCVerifyCacheSubscription
    60,  // 1006 -> k_EMsgGCNameItem
    127,  // 1007 -> k_EMsgGCUnlockCrate
    128,  // 1008 -> k_EMsgGCUnlockCrateResponse
    62,  // 1009 -> k_EMsgGCPaintItem
    63,  // 1010 -> k_EMsgGCPaintItemResponse
    39,  // 1011 -> k_EMsgGCGoldenWrenchBroadcast
    54,  // 1012 -> k_EMsgGCMOTDRequest
    55,  // 1013 -> k_EMsgGCMOTDRequestResponse
    1,  // 1014 -> k_EMsgGCAddItemToSocket_DEPRECATED
    0,  // 1015 -> k_EMsgGCAddItemToSocketResponse_DEPRECATED
    2,  // 1016 -> k_EMsgGCAddSocketToBaseItem_DEPRECATED
    4,  // 1017 -> k_EMsgGCAddSocketToItem_DEPRECATED
    3,  // 1018 -> k_EMsgGCAddSocketToItemResponse_DEPRECATED
    57,  // 1019 -> k_EMsgGCNameBaseItem
    58,  // 1020 -> k_EMsgGCNameBaseItemResponse
    75,  // 1021 -> k_EMsgGCRemoveSocketItem_DEPRECATED
    74,  // 1022 -> k_EMsgGCRemoveSocketItemResponse_DEPRECATED
    26,  // 1023 -> k_EMsgGCCustomizeItemTexture
    27,  // 1024 -> k_EMsgGCCustomizeItemTextureResponse
    134,  // 1025 -> k_EMsgGCUseItemRequest
    135,  // 1026 -> k_EMsgGCUseItemResponse
    38,  // 1027 -> k_EMsgGCGiftedItems_DEPRECATED
    70,  // 1030 -> k_EMsgGCRemoveItemName
    71,  // 1031 -> k_EMsgGCRemoveItemPaint
    35,  // 1032 -> k_EMsgGCGiftWrapItem
    36,  // 1033 -> k_EMsgGCGiftWrapItemResponse
    29,  // 1034 -> k_EMsgGCDeliverGift
    30,  // 1035 -> k_EMsgGCDeliverGiftResponseGiver
    31,  // 1036 -> k_EMsgGCDeliverGiftResponseReceiver
    131,  // 1037 -> k_EMsgGCUnwrapGiftRequest
    132,  // 1038 -> k_EMsgGCUnwrapGiftResponse
    88,  // 1039 -> k_EMsgGCSetItemStyle
    136,  // 1040 -> k_EMsgGCUsedClaimCodeItem
    90,  // 1041 -> k_EMsgGCSortItems
    143,  // 1042 -> k_EMsgGC_RevolvingLootList_DEPRECATED
    50,  // 1043 -> k_EMsgGCLookupAccount
    53,  // 1044 -> k_EMsgGCLookupAccountResponse
    51,  // 1045 -> k_EMsgGCLookupAccountName
    52,  // 1046 -> k_EMsgGCLookupAccountNameResponse
    133,  // 1049 -> k_EMsgGCUpdateItemSchema
    68,  // 1051 -> k_EMsgGCRemoveCustomTexture
    69,  // 1052 -> k_EMsgGCRemoveCustomTextureResponse
    72,  // 1053 -> k_EMsgGCRemoveMakersMark
    73,  // 1054 -> k_EMsgGCRemoveMakersMarkResponse
    76,  // 1055 -> k_EMsgGCRemoveUniqueCraftIndex
    77,  // 1056 -> k_EMsgGCRemoveUniqueCraftIndexResponse
    81,  // 1057 -> k_EMsgGCSaxxyBroadcast
    13,  // 1058 -> k_EMsgGCBackpackSortFinished
    6,  // 1059 -> k_EMsgGCAdjustItemEquippedState
    22,  // 1061 -> k_EMsgGCCollectItem
    41,  // 1062 -> k_EMsgGCItemAcknowledged__DEPRECATED
    141,  // 1065 -> k_EMsgGC_ReportAbuse
    142,  // 1066 -> k_EMsgGC_ReportAbuseResponse
    61,  // 1068 -> k_EMsgGCNameItemNotification
    8,  // 1069 -> k_EMsgGCApplyConsumableEffects
    23,  // 1070 -> k_EMsgGCConsumableExhausted
    89,  // 1071 -> k_EMsgGCShowItemsPickedUp
    20,  // 1072 -> k_EMsgGCClientDisplayNotification
    12,  // 1073 -> k_EMsgGCApplyStrangePart
    139,  // 1074 -> k_EMsgGC_IncrementKillCountAttribute
    140,  // 1075 -> k_EMsgGC_IncrementKillCountResponse
    10,  // 1076 -> k_EMsgGCApplyPennantUpgrade
    87,  // 1077 -> k_EMsgGCSetItemPositions
    9,  // 1078 -> k_EMsgGCApplyEggEssence
    59,  // 1079 -> k_EMsgGCNameEggEssenceResponse
    65,  // 1080 -> k_EMsgGCPaintKitItem
    64,  // 1081 -> k_EMsgGCPaintKitBaseItem
    66,  // 1082 -> k_EMsgGCPaintKitItemResponse
    37,  // 1083 -> k_EMsgGCGiftedItems
    129,  // 1084 -> k_EMsgGCUnlockItemStyle
    130,  // 1085 -> k_EMsgGCUnlockItemStyleResponse
    11,  // 1086 -> k_EMsgGCApplySticker
    40,  // 1087 -> k_EMsgGCItemAcknowledged
    91,  // 1088 -> k_EMsgGCStatTrakSwap
    137,  // 1089 -> k_EMsgGCUserTrackTimePlayedConsecutively
    42,  // 1090 -> k_EMsgGCItemCustomizationNotification
    56,  // 1091 -> k_EMsgGCModifyItemAttribute
    17,  // 1092 -> k_EMsgGCCasketItemAdd
    18,  // 1093 -> k_EMsgGCCasketItemExtract
    19,  // 1094 -> k_EMsgGCCasketItemLoadContents
    113,  // 1500 -> k_EMsgGCTradingBase
    116,  // 1501 -> k_EMsgGCTrading_InitiateTradeRequest
    117,  // 1502 -> k_EMsgGCTrading_InitiateTradeResponse
    123,  // 1503 -> k_EMsgGCTrading_StartSession
    121,  // 1504 -> k_EMsgGCTrading_SetItem
    119,  // 1505 -> k_EMsgGCTrading_RemoveItem
    126,  // 1506 -> k_EMsgGCTrading_UpdateTradeInfo
    122,  // 1507 -> k_EMsgGCTrading_SetReadiness
    118,  // 1508 -> k_EMsgGCTrading_ReadinessResponse
    120,  // 1509 -> k_EMsgGCTrading_SessionClosed
    114,  // 1510 -> k_EMsgGCTrading_CancelSession
    124,  // 1511 -> k_EMsgGCTrading_TradeChatMsg
    115,  // 1512 -> k_EMsgGCTrading_ConfirmOffer
    125,  // 1513 -> k_EMsgGCTrading_TradeTypingChatMsg
    83,  // 1601 -> k_EMsgGCServerBrowser_FavoriteServer
    82,  // 1602 -> k_EMsgGCServerBrowser_BlacklistServer
    84,  // 1700 -> k_EMsgGCServerRentalsBase
    43,  // 1701 -> k_EMsgGCItemPreviewCheckStatus
    49,  // 1702 -> k_EMsgGCItemPreviewStatusResponse
    47,  // 1703 -> k_EMsgGCItemPreviewRequest
    48,  // 1704 -> k_EMsgGCItemPreviewRequestResponse
    44,  // 1705 -> k_EMsgGCItemPreviewExpire
    45,  // 1706 -> k_EMsgGCItemPreviewExpireNotification
    46,  // 1707 -> k_EMsgGCItemPreviewItemBoughtNotification
    32,  // 2001 -> k_EMsgGCDev_NewItemRequest
    33,  // 2002 -> k_EMsgGCDev_NewItemRequestResponse
    34,  // 2003 -> k_EMsgGCDev_PaintKitDropItem
    92,  // 2500 -> k_EMsgGCStoreGetUserData
    93,  // 2501 -> k_EMsgGCStoreGetUserDataResponse
    101,  // 2502 -> k_EMsgGCStorePurchaseInit_DEPRECATED
    100,  // 2503 -> k_EMsgGCStorePurchaseInitResponse_DEPRECATED
    96,  // 2504 -> k_EMsgGCStorePurchaseFinalize
    97,  // 2505 -> k_EMsgGCStorePurchaseFinalizeResponse
    94,  // 2506 -> k_EMsgGCStorePurchaseCancel
    95,  // 2507 -> k_EMsgGCStorePurchaseCancelResponse
    102,  // 2508 -> k_EMsgGCStorePurchaseQueryTxn
    103,  // 2509 -> k_EMsgGCStorePurchaseQueryTxnResponse
    98,  // 2510 -> k_EMsgGCStorePurchaseInit
    99,  // 2511 -> k_EMsgGCStorePurchaseInitResponse
    14,  // 2512 -> k_EMsgGCBannedWordListRequest
    15,  // 2513 -> k_EMsgGCBannedWordListResponse
    104,  // 2514 -> k_EMsgGCToGCBannedWordListBroadcast
    105,  // 2515 -> k_EMsgGCToGCBannedWordListUpdated
    108,  // 2516 -> k_EMsgGCToGCDirtySDOCache
    107,  // 2517 -> k_EMsgGCToGCDirtyMultipleSDOCache
    111,  // 2518 -> k_EMsgGCToGCUpdateSQLKeyValue
    109,  // 2519 -> k_EMsgGCToGCIsTrustedServer
    110,  // 2520 -> k_EMsgGCToGCIsTrustedServerResponse
    106,  // 2521 -> k_EMsgGCToGCBroadcastConsoleCommand
    85,  // 2522 -> k_EMsgGCServerVersionUpdated
    112,  // 2524 -> k_EMsgGCToGCWebAPIAccountChanged
    78,  // 2525 -> k_EMsgGCRequestAnnouncements
    79,  // 2526 -> k_EMsgGCRequestAnnouncementsResponse
    80,  // 2527 -> k_EMsgGCRequestPassportItemGrant
    21,  // 2528 -> k_EMsgGCClientVersionUpdated
    7,  // 2529 -> k_EMsgGCAdjustItemEquippedStateMulti
    67,  // 2530 -> k_EMsgGCRecurringSubscriptionStatus
    5,  // 2531 -> k_EMsgGCAdjustEquipSlots
};

[[nodiscard]] bool EGCItemMsg_Parse(::absl::string_view name,
                                  EGCItemMsg* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EGCItemMsg_entries, 144, name, &int_value);
  if (success) {
    *value = static_cast<EGCItemMsg>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    EGCItemMsg_strings[144] = {};

[[nodiscard]] const ::std::string& EGCItemMsg_Name(EGCItemMsg value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      EGCItemMsg_entries, EGCItemMsg_entries_by_number, 144,
      EGCItemMsg_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(EGCItemMsg_entries,
                                  EGCItemMsg_entries_by_number,
                                  144, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : EGCItemMsg_strings[idx].get();
}
PROTOBUF_CONSTINIT const uint32_t EGCMsgResponse_internal_data_[] = {
    720896u, 0u, };
static const char EGCMsgResponse_names[] = {
    "k_EGCMsgCommitUnfinalized"
    "k_EGCMsgFailedToCreate"
    "k_EGCMsgLimitExceeded"
    "k_EGCMsgResponseDenied"
    "k_EGCMsgResponseInvalid"
    "k_EGCMsgResponseNoMatch"
    "k_EGCMsgResponseNotLoggedOn"
    "k_EGCMsgResponseOK"
    "k_EGCMsgResponseServerError"
    "k_EGCMsgResponseTimeout"
    "k_EGCMsgResponseUnknownError"
};

static const ::google::protobuf::internal::EnumEntry EGCMsgResponse_entries[] = {
    {{&EGCMsgResponse_names[0], 25}, 10},
    {{&EGCMsgResponse_names[25], 22}, 8},
    {{&EGCMsgResponse_names[47], 21}, 9},
    {{&EGCMsgResponse_names[68], 22}, 1},
    {{&EGCMsgResponse_names[90], 23}, 4},
    {{&EGCMsgResponse_names[113], 23}, 5},
    {{&EGCMsgResponse_names[136], 27}, 7},
    {{&EGCMsgResponse_names[163], 18}, 0},
    {{&EGCMsgResponse_names[181], 27}, 2},
    {{&EGCMsgResponse_names[208], 23}, 3},
    {{&EGCMsgResponse_names[231], 28}, 6},
};

static const int EGCMsgResponse_entries_by_number[] = {
    7,  // 0 -> k_EGCMsgResponseOK
    3,  // 1 -> k_EGCMsgResponseDenied
    8,  // 2 -> k_EGCMsgResponseServerError
    9,  // 3 -> k_EGCMsgResponseTimeout
    4,  // 4 -> k_EGCMsgResponseInvalid
    5,  // 5 -> k_EGCMsgResponseNoMatch
    10,  // 6 -> k_EGCMsgResponseUnknownError
    6,  // 7 -> k_EGCMsgResponseNotLoggedOn
    1,  // 8 -> k_EGCMsgFailedToCreate
    2,  // 9 -> k_EGCMsgLimitExceeded
    0,  // 10 -> k_EGCMsgCommitUnfinalized
};

[[nodiscard]] bool EGCMsgResponse_Parse(::absl::string_view name,
                                  EGCMsgResponse* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EGCMsgResponse_entries, 11, name, &int_value);
  if (success) {
    *value = static_cast<EGCMsgResponse>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    EGCMsgResponse_strings[11] = {};

[[nodiscard]] const ::std::string& EGCMsgResponse_Name(EGCMsgResponse value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      EGCMsgResponse_entries, EGCMsgResponse_entries_by_number, 11,
      EGCMsgResponse_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(EGCMsgResponse_entries,
                                  EGCMsgResponse_entries_by_number,
                                  11, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : EGCMsgResponse_strings[idx].get();
}
PROTOBUF_CONSTINIT const uint32_t EUnlockStyle_internal_data_[] = {
    393216u, 0u, };
static const char EUnlockStyle_names[] = {
    "k_UnlockStyle_Failed_CantAfford"
    "k_UnlockStyle_Failed_CantAffordAttrib"
    "k_UnlockStyle_Failed_CantCommit"
    "k_UnlockStyle_Failed_CantLockCache"
    "k_UnlockStyle_Failed_PreReq"
    "k_UnlockStyle_Succeeded"
};

static const ::google::protobuf::internal::EnumEntry EUnlockStyle_entries[] = {
    {{&EUnlockStyle_names[0], 31}, 2},
    {{&EUnlockStyle_names[31], 37}, 5},
    {{&EUnlockStyle_names[68], 31}, 3},
    {{&EUnlockStyle_names[99], 34}, 4},
    {{&EUnlockStyle_names[133], 27}, 1},
    {{&EUnlockStyle_names[160], 23}, 0},
};

static const int EUnlockStyle_entries_by_number[] = {
    5,  // 0 -> k_UnlockStyle_Succeeded
    4,  // 1 -> k_UnlockStyle_Failed_PreReq
    0,  // 2 -> k_UnlockStyle_Failed_CantAfford
    2,  // 3 -> k_UnlockStyle_Failed_CantCommit
    3,  // 4 -> k_UnlockStyle_Failed_CantLockCache
    1,  // 5 -> k_UnlockStyle_Failed_CantAffordAttrib
};

[[nodiscard]] bool EUnlockStyle_Parse(::absl::string_view name,
                                  EUnlockStyle* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EUnlockStyle_entries, 6, name, &int_value);
  if (success) {
    *value = static_cast<EUnlockStyle>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    EUnlockStyle_strings[6] = {};

[[nodiscard]] const ::std::string& EUnlockStyle_Name(EUnlockStyle value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      EUnlockStyle_entries, EUnlockStyle_entries_by_number, 6,
      EUnlockStyle_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(EUnlockStyle_entries,
                                  EUnlockStyle_entries_by_number,
                                  6, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : EUnlockStyle_strings[idx].get();
}
PROTOBUF_CONSTINIT const uint32_t EGCItemCustomizationNotification_internal_data_[] = {
    263150u, 327776u, 1049150u, 2048u, 118784u, 9204u, 9179u, 9209u, 9178u, 9185u, };
static const char EGCItemCustomizationNotification_names[] = {
    "k_EGCItemCustomizationNotification_ActivateFanToken"
    "k_EGCItemCustomizationNotification_ActivateOperationCoin"
    "k_EGCItemCustomizationNotification_ApplyPatch"
    "k_EGCItemCustomizationNotification_ApplySticker"
    "k_EGCItemCustomizationNotification_CasketAdded"
    "k_EGCItemCustomizationNotification_CasketContents"
    "k_EGCItemCustomizationNotification_CasketInvFull"
    "k_EGCItemCustomizationNotification_CasketRemoved"
    "k_EGCItemCustomizationNotification_CasketTooFull"
    "k_EGCItemCustomizationNotification_ClientRedeemMissionReward"
    "k_EGCItemCustomizationNotification_GenerateSouvenir"
    "k_EGCItemCustomizationNotification_GraffitiUnseal"
    "k_EGCItemCustomizationNotification_NameBaseItem"
    "k_EGCItemCustomizationNotification_NameItem"
    "k_EGCItemCustomizationNotification_RemoveItemName"
    "k_EGCItemCustomizationNotification_RemovePatch"
    "k_EGCItemCustomizationNotification_RemoveSticker"
    "k_EGCItemCustomizationNotification_StatTrakSwap"
    "k_EGCItemCustomizationNotification_UnlockCrate"
    "k_EGCItemCustomizationNotification_XRayItemClaim"
    "k_EGCItemCustomizationNotification_XRayItemReveal"
};

static const ::google::protobuf::internal::EnumEntry EGCItemCustomizationNotification_entries[] = {
    {{&EGCItemCustomizationNotification_names[0], 51}, 9178},
    {{&EGCItemCustomizationNotification_names[51], 56}, 9179},
    {{&EGCItemCustomizationNotification_names[107], 45}, 1090},
    {{&EGCItemCustomizationNotification_names[152], 47}, 1086},
    {{&EGCItemCustomizationNotification_names[199], 46}, 1013},
    {{&EGCItemCustomizationNotification_names[245], 49}, 1012},
    {{&EGCItemCustomizationNotification_names[294], 48}, 1015},
    {{&EGCItemCustomizationNotification_names[342], 48}, 1014},
    {{&EGCItemCustomizationNotification_names[390], 48}, 1011},
    {{&EGCItemCustomizationNotification_names[438], 60}, 9209},
    {{&EGCItemCustomizationNotification_names[498], 51}, 9204},
    {{&EGCItemCustomizationNotification_names[549], 49}, 9185},
    {{&EGCItemCustomizationNotification_names[598], 47}, 1019},
    {{&EGCItemCustomizationNotification_names[645], 43}, 1006},
    {{&EGCItemCustomizationNotification_names[688], 49}, 1030},
    {{&EGCItemCustomizationNotification_names[737], 46}, 1089},
    {{&EGCItemCustomizationNotification_names[783], 48}, 1053},
    {{&EGCItemCustomizationNotification_names[831], 47}, 1088},
    {{&EGCItemCustomizationNotification_names[878], 46}, 1007},
    {{&EGCItemCustomizationNotification_names[924], 48}, 1009},
    {{&EGCItemCustomizationNotification_names[972], 49}, 1008},
};

static const int EGCItemCustomizationNotification_entries_by_number[] = {
    13,  // 1006 -> k_EGCItemCustomizationNotification_NameItem
    18,  // 1007 -> k_EGCItemCustomizationNotification_UnlockCrate
    20,  // 1008 -> k_EGCItemCustomizationNotification_XRayItemReveal
    19,  // 1009 -> k_EGCItemCustomizationNotification_XRayItemClaim
    8,  // 1011 -> k_EGCItemCustomizationNotification_CasketTooFull
    5,  // 1012 -> k_EGCItemCustomizationNotification_CasketContents
    4,  // 1013 -> k_EGCItemCustomizationNotification_CasketAdded
    7,  // 1014 -> k_EGCItemCustomizationNotification_CasketRemoved
    6,  // 1015 -> k_EGCItemCustomizationNotification_CasketInvFull
    12,  // 1019 -> k_EGCItemCustomizationNotification_NameBaseItem
    14,  // 1030 -> k_EGCItemCustomizationNotification_RemoveItemName
    16,  // 1053 -> k_EGCItemCustomizationNotification_RemoveSticker
    3,  // 1086 -> k_EGCItemCustomizationNotification_ApplySticker
    17,  // 1088 -> k_EGCItemCustomizationNotification_StatTrakSwap
    15,  // 1089 -> k_EGCItemCustomizationNotification_RemovePatch
    2,  // 1090 -> k_EGCItemCustomizationNotification_ApplyPatch
    0,  // 9178 -> k_EGCItemCustomizationNotification_ActivateFanToken
    1,  // 9179 -> k_EGCItemCustomizationNotification_ActivateOperationCoin
    11,  // 9185 -> k_EGCItemCustomizationNotification_GraffitiUnseal
    10,  // 9204 -> k_EGCItemCustomizationNotification_GenerateSouvenir
    9,  // 9209 -> k_EGCItemCustomizationNotification_ClientRedeemMissionReward
};

[[nodiscard]] bool EGCItemCustomizationNotification_Parse(::absl::string_view name,
                                  EGCItemCustomizationNotification* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      EGCItemCustomizationNotification_entries, 21, name, &int_value);
  if (success) {
    *value = static_cast<EGCItemCustomizationNotification>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    EGCItemCustomizationNotification_strings[21] = {};

[[nodiscard]] const ::std::string& EGCItemCustomizationNotification_Name(EGCItemCustomizationNotification value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      EGCItemCustomizationNotification_entries, EGCItemCustomizationNotification_entries_by_number, 21,
      EGCItemCustomizationNotification_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(EGCItemCustomizationNotification_entries,
                                  EGCItemCustomizationNotification_entries_by_number,
                                  21, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : EGCItemCustomizationNotification_strings[idx].get();
}
// ===================================================================

class CMsgGCGiftedItems::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CMsgGCGiftedItems>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_._has_bits_);
};

CMsgGCGiftedItems::CMsgGCGiftedItems(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCGiftedItems_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGCGiftedItems)
}
PROTOBUF_NDEBUG_INLINE CMsgGCGiftedItems::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CMsgGCGiftedItems& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        recipients_accountids_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::CMsgGCGiftedItems,
            PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.recipients_accountids_)>()
        , from.recipients_accountids_}
        #else
        recipients_accountids_ { visibility, arena, from.recipients_accountids_ }
        #endif
     {}

CMsgGCGiftedItems::CMsgGCGiftedItems(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CMsgGCGiftedItems& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCGiftedItems_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CMsgGCGiftedItems* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, accountid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, accountid_),
           offsetof(Impl_, num_eligible_recipients_) -
               offsetof(Impl_, accountid_) +
               sizeof(Impl_::num_eligible_recipients_));

  // @@protoc_insertion_point(copy_constructor:CMsgGCGiftedItems)
}
PROTOBUF_NDEBUG_INLINE CMsgGCGiftedItems::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        recipients_accountids_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::CMsgGCGiftedItems,
            PROTOBUF_FIELD_OFFSET(::CMsgGCGiftedItems, _impl_.recipients_accountids_)>()
        }
        #else
        recipients_accountids_ { visibility, arena }
        #endif
     {}

inline void CMsgGCGiftedItems::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, accountid_),
           0,
           offsetof(Impl_, num_eligible_recipients_) -
               offsetof(Impl_, accountid_) +
               sizeof(Impl_::num_eligible_recipients_));
}
CMsgGCGiftedItems::~CMsgGCGiftedItems() {
  // @@protoc_insertion_point(destructor:CMsgGCGiftedItems)
  SharedDtor(*this);
}
inline void CMsgGCGiftedItems::SharedDtor(MessageLite& self) {
  CMsgGCGiftedItems& this_ = static_cast<CMsgGCGiftedItems&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CMsgGCGiftedItems::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CMsgGCGiftedItems(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto CMsgGCGiftedItems::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CMsgGCGiftedItems),
                                            alignof(CMsgGCGiftedItems));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto CMsgGCGiftedItems::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.recipients_accountids_) +
          decltype(CMsgGCGiftedItems::_impl_.recipients_accountids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CMsgGCGiftedItems), alignof(CMsgGCGiftedItems), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CMsgGCGiftedItems::PlacementNew_,
                                 sizeof(CMsgGCGiftedItems),
                                 alignof(CMsgGCGiftedItems));
  }
}
#endif
constexpr auto CMsgGCGiftedItems::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<18>{
      {
          &_CMsgGCGiftedItems_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CMsgGCGiftedItems::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<CMsgGCGiftedItems>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CMsgGCGiftedItems::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<CMsgGCGiftedItems>(), &CMsgGCGiftedItems::ByteSizeLong,
              &CMsgGCGiftedItems::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_._cached_size_),
          true,
      },
      "CMsgGCGiftedItems",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<18> CMsgGCGiftedItems_class_data_ =
    CMsgGCGiftedItems::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CMsgGCGiftedItems::GetClassData() const {
  return CMsgGCGiftedItems_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
CMsgGCGiftedItems::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CMsgGCGiftedItems_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgGCGiftedItems>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 accountid = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.accountid_)}},
    // optional uint32 giftdefindex = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.giftdefindex_)}},
    // optional uint32 max_gifts_possible = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.max_gifts_possible_)}},
    // optional uint32 num_eligible_recipients = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.num_eligible_recipients_)}},
    // repeated uint32 recipients_accountids = 5;
    {::_pbi::TcParser::FastV32R1,
     {40, 0, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.recipients_accountids_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 accountid = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.accountid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 giftdefindex = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.giftdefindex_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 max_gifts_possible = 3;
    {PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.max_gifts_possible_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 num_eligible_recipients = 4;
    {PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.num_eligible_recipients_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated uint32 recipients_accountids = 5;
    {PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.recipients_accountids_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CMsgGCGiftedItems::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCGiftedItems)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.recipients_accountids_.Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.accountid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.num_eligible_recipients_) -
        reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.num_eligible_recipients_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CMsgGCGiftedItems::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CMsgGCGiftedItems& this_ = static_cast<const CMsgGCGiftedItems&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CMsgGCGiftedItems::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CMsgGCGiftedItems& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCGiftedItems)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 accountid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_accountid(), target);
  }

  // optional uint32 giftdefindex = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_giftdefindex(), target);
  }

  // optional uint32 max_gifts_possible = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_max_gifts_possible(), target);
  }

  // optional uint32 num_eligible_recipients = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_num_eligible_recipients(), target);
  }

  // repeated uint32 recipients_accountids = 5;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_recipients_accountids_size(); i < n; ++i) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_recipients_accountids().Get(i), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCGiftedItems)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CMsgGCGiftedItems::ByteSizeLong(const MessageLite& base) {
  const CMsgGCGiftedItems& this_ = static_cast<const CMsgGCGiftedItems&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CMsgGCGiftedItems::ByteSizeLong() const {
  const CMsgGCGiftedItems& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CMsgGCGiftedItems)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated uint32 recipients_accountids = 5;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::_pbi::WireFormatLite::UInt32Size(
          this_._internal_recipients_accountids());
      ::size_t tag_size = ::size_t{1} *
          ::_pbi::FromIntSize(this_._internal_recipients_accountids_size());
      total_size += tag_size + data_size;
    }
    // optional uint32 accountid = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_accountid());
    }
    // optional uint32 giftdefindex = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_giftdefindex());
    }
    // optional uint32 max_gifts_possible = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_max_gifts_possible());
    }
    // optional uint32 num_eligible_recipients = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_num_eligible_recipients());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CMsgGCGiftedItems::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CMsgGCGiftedItems*>(&to_msg);
  auto& from = static_cast<const CMsgGCGiftedItems&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCGiftedItems)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_recipients_accountids()->MergeFrom(from._internal_recipients_accountids());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.accountid_ = from._impl_.accountid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.giftdefindex_ = from._impl_.giftdefindex_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.max_gifts_possible_ = from._impl_.max_gifts_possible_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.num_eligible_recipients_ = from._impl_.num_eligible_recipients_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void CMsgGCGiftedItems::CopyFrom(const CMsgGCGiftedItems& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCGiftedItems)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgGCGiftedItems::InternalSwap(CMsgGCGiftedItems* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.recipients_accountids_.InternalSwap(&other->_impl_.recipients_accountids_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.num_eligible_recipients_)
      + sizeof(CMsgGCGiftedItems::_impl_.num_eligible_recipients_)
      - PROTOBUF_FIELD_OFFSET(CMsgGCGiftedItems, _impl_.accountid_)>(
          reinterpret_cast<char*>(&_impl_.accountid_),
          reinterpret_cast<char*>(&other->_impl_.accountid_));
}

// ===================================================================

class CMsgCasketItem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CMsgCasketItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_._has_bits_);
};

CMsgCasketItem::CMsgCasketItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgCasketItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgCasketItem)
}
CMsgCasketItem::CMsgCasketItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgCasketItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgCasketItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CMsgCasketItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CMsgCasketItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, casket_item_id_),
           0,
           offsetof(Impl_, item_item_id_) -
               offsetof(Impl_, casket_item_id_) +
               sizeof(Impl_::item_item_id_));
}
CMsgCasketItem::~CMsgCasketItem() {
  // @@protoc_insertion_point(destructor:CMsgCasketItem)
  SharedDtor(*this);
}
inline void CMsgCasketItem::SharedDtor(MessageLite& self) {
  CMsgCasketItem& this_ = static_cast<CMsgCasketItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CMsgCasketItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CMsgCasketItem(arena);
}
constexpr auto CMsgCasketItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CMsgCasketItem),
                                            alignof(CMsgCasketItem));
}
constexpr auto CMsgCasketItem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_CMsgCasketItem_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CMsgCasketItem::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<CMsgCasketItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CMsgCasketItem::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<CMsgCasketItem>(), &CMsgCasketItem::ByteSizeLong,
              &CMsgCasketItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_._cached_size_),
          true,
      },
      "CMsgCasketItem",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> CMsgCasketItem_class_data_ =
    CMsgCasketItem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CMsgCasketItem::GetClassData() const {
  return CMsgCasketItem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
CMsgCasketItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CMsgCasketItem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgCasketItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint64 item_item_id = 2;
    {::_pbi::TcParser::FastV64S1,
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_.item_item_id_)}},
    // optional uint64 casket_item_id = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_.casket_item_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 casket_item_id = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_.casket_item_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 item_item_id = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_.item_item_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CMsgCasketItem::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgCasketItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.casket_item_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.item_item_id_) -
        reinterpret_cast<char*>(&_impl_.casket_item_id_)) + sizeof(_impl_.item_item_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CMsgCasketItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CMsgCasketItem& this_ = static_cast<const CMsgCasketItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CMsgCasketItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CMsgCasketItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CMsgCasketItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 casket_item_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_casket_item_id(), target);
  }

  // optional uint64 item_item_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this_._internal_item_item_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgCasketItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CMsgCasketItem::ByteSizeLong(const MessageLite& base) {
  const CMsgCasketItem& this_ = static_cast<const CMsgCasketItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CMsgCasketItem::ByteSizeLong() const {
  const CMsgCasketItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CMsgCasketItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional uint64 casket_item_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_casket_item_id());
    }
    // optional uint64 item_item_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_item_item_id());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CMsgCasketItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CMsgCasketItem*>(&to_msg);
  auto& from = static_cast<const CMsgCasketItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgCasketItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.casket_item_id_ = from._impl_.casket_item_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.item_item_id_ = from._impl_.item_item_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void CMsgCasketItem::CopyFrom(const CMsgCasketItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CMsgCasketItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgCasketItem::InternalSwap(CMsgCasketItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_.item_item_id_)
      + sizeof(CMsgCasketItem::_impl_.item_item_id_)
      - PROTOBUF_FIELD_OFFSET(CMsgCasketItem, _impl_.casket_item_id_)>(
          reinterpret_cast<char*>(&_impl_.casket_item_id_),
          reinterpret_cast<char*>(&other->_impl_.casket_item_id_));
}

// ===================================================================

class CMsgGCUserTrackTimePlayedConsecutively::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CMsgGCUserTrackTimePlayedConsecutively>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgGCUserTrackTimePlayedConsecutively, _impl_._has_bits_);
};

CMsgGCUserTrackTimePlayedConsecutively::CMsgGCUserTrackTimePlayedConsecutively(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCUserTrackTimePlayedConsecutively_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGCUserTrackTimePlayedConsecutively)
}
CMsgGCUserTrackTimePlayedConsecutively::CMsgGCUserTrackTimePlayedConsecutively(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgGCUserTrackTimePlayedConsecutively& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCUserTrackTimePlayedConsecutively_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CMsgGCUserTrackTimePlayedConsecutively::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CMsgGCUserTrackTimePlayedConsecutively::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.state_ = {};
}
CMsgGCUserTrackTimePlayedConsecutively::~CMsgGCUserTrackTimePlayedConsecutively() {
  // @@protoc_insertion_point(destructor:CMsgGCUserTrackTimePlayedConsecutively)
  SharedDtor(*this);
}
inline void CMsgGCUserTrackTimePlayedConsecutively::SharedDtor(MessageLite& self) {
  CMsgGCUserTrackTimePlayedConsecutively& this_ = static_cast<CMsgGCUserTrackTimePlayedConsecutively&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CMsgGCUserTrackTimePlayedConsecutively::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CMsgGCUserTrackTimePlayedConsecutively(arena);
}
constexpr auto CMsgGCUserTrackTimePlayedConsecutively::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CMsgGCUserTrackTimePlayedConsecutively),
                                            alignof(CMsgGCUserTrackTimePlayedConsecutively));
}
constexpr auto CMsgGCUserTrackTimePlayedConsecutively::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<39>{
      {
          &_CMsgGCUserTrackTimePlayedConsecutively_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CMsgGCUserTrackTimePlayedConsecutively::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<CMsgGCUserTrackTimePlayedConsecutively>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CMsgGCUserTrackTimePlayedConsecutively::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<CMsgGCUserTrackTimePlayedConsecutively>(), &CMsgGCUserTrackTimePlayedConsecutively::ByteSizeLong,
              &CMsgGCUserTrackTimePlayedConsecutively::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CMsgGCUserTrackTimePlayedConsecutively, _impl_._cached_size_),
          true,
      },
      "CMsgGCUserTrackTimePlayedConsecutively",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<39> CMsgGCUserTrackTimePlayedConsecutively_class_data_ =
    CMsgGCUserTrackTimePlayedConsecutively::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CMsgGCUserTrackTimePlayedConsecutively::GetClassData() const {
  return CMsgGCUserTrackTimePlayedConsecutively_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
CMsgGCUserTrackTimePlayedConsecutively::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgGCUserTrackTimePlayedConsecutively, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CMsgGCUserTrackTimePlayedConsecutively_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgGCUserTrackTimePlayedConsecutively>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint32 state = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCUserTrackTimePlayedConsecutively, _impl_.state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 state = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgGCUserTrackTimePlayedConsecutively, _impl_.state_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CMsgGCUserTrackTimePlayedConsecutively::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCUserTrackTimePlayedConsecutively)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.state_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CMsgGCUserTrackTimePlayedConsecutively::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CMsgGCUserTrackTimePlayedConsecutively& this_ = static_cast<const CMsgGCUserTrackTimePlayedConsecutively&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CMsgGCUserTrackTimePlayedConsecutively::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CMsgGCUserTrackTimePlayedConsecutively& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCUserTrackTimePlayedConsecutively)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 state = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_state(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCUserTrackTimePlayedConsecutively)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CMsgGCUserTrackTimePlayedConsecutively::ByteSizeLong(const MessageLite& base) {
  const CMsgGCUserTrackTimePlayedConsecutively& this_ = static_cast<const CMsgGCUserTrackTimePlayedConsecutively&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CMsgGCUserTrackTimePlayedConsecutively::ByteSizeLong() const {
  const CMsgGCUserTrackTimePlayedConsecutively& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CMsgGCUserTrackTimePlayedConsecutively)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional uint32 state = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_state());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CMsgGCUserTrackTimePlayedConsecutively::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CMsgGCUserTrackTimePlayedConsecutively*>(&to_msg);
  auto& from = static_cast<const CMsgGCUserTrackTimePlayedConsecutively&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCUserTrackTimePlayedConsecutively)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.state_ = from._impl_.state_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void CMsgGCUserTrackTimePlayedConsecutively::CopyFrom(const CMsgGCUserTrackTimePlayedConsecutively& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCUserTrackTimePlayedConsecutively)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgGCUserTrackTimePlayedConsecutively::InternalSwap(CMsgGCUserTrackTimePlayedConsecutively* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.state_, other->_impl_.state_);
}

// ===================================================================

class CMsgGCItemCustomizationNotification::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CMsgGCItemCustomizationNotification>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_._has_bits_);
};

CMsgGCItemCustomizationNotification::CMsgGCItemCustomizationNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCItemCustomizationNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGCItemCustomizationNotification)
}
PROTOBUF_NDEBUG_INLINE CMsgGCItemCustomizationNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CMsgGCItemCustomizationNotification& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        item_id_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::CMsgGCItemCustomizationNotification,
            PROTOBUF_FIELD_OFFSET(::CMsgGCItemCustomizationNotification, _impl_.item_id_)>()
        , from.item_id_}
        #else
        item_id_ { visibility, arena, from.item_id_ }
        #endif
     {}

CMsgGCItemCustomizationNotification::CMsgGCItemCustomizationNotification(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CMsgGCItemCustomizationNotification& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CMsgGCItemCustomizationNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CMsgGCItemCustomizationNotification* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.request_ = from._impl_.request_;

  // @@protoc_insertion_point(copy_constructor:CMsgGCItemCustomizationNotification)
}
PROTOBUF_NDEBUG_INLINE CMsgGCItemCustomizationNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        item_id_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::CMsgGCItemCustomizationNotification,
            PROTOBUF_FIELD_OFFSET(::CMsgGCItemCustomizationNotification, _impl_.item_id_)>()
        }
        #else
        item_id_ { visibility, arena }
        #endif
     {}

inline void CMsgGCItemCustomizationNotification::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.request_ = {};
}
CMsgGCItemCustomizationNotification::~CMsgGCItemCustomizationNotification() {
  // @@protoc_insertion_point(destructor:CMsgGCItemCustomizationNotification)
  SharedDtor(*this);
}
inline void CMsgGCItemCustomizationNotification::SharedDtor(MessageLite& self) {
  CMsgGCItemCustomizationNotification& this_ = static_cast<CMsgGCItemCustomizationNotification&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CMsgGCItemCustomizationNotification::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CMsgGCItemCustomizationNotification(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto CMsgGCItemCustomizationNotification::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CMsgGCItemCustomizationNotification),
                                            alignof(CMsgGCItemCustomizationNotification));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto CMsgGCItemCustomizationNotification::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_.item_id_) +
          decltype(CMsgGCItemCustomizationNotification::_impl_.item_id_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CMsgGCItemCustomizationNotification), alignof(CMsgGCItemCustomizationNotification), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CMsgGCItemCustomizationNotification::PlacementNew_,
                                 sizeof(CMsgGCItemCustomizationNotification),
                                 alignof(CMsgGCItemCustomizationNotification));
  }
}
#endif
constexpr auto CMsgGCItemCustomizationNotification::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<36>{
      {
          &_CMsgGCItemCustomizationNotification_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CMsgGCItemCustomizationNotification::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<CMsgGCItemCustomizationNotification>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CMsgGCItemCustomizationNotification::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<CMsgGCItemCustomizationNotification>(), &CMsgGCItemCustomizationNotification::ByteSizeLong,
              &CMsgGCItemCustomizationNotification::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_._cached_size_),
          true,
      },
      "CMsgGCItemCustomizationNotification",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<36> CMsgGCItemCustomizationNotification_class_data_ =
    CMsgGCItemCustomizationNotification::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CMsgGCItemCustomizationNotification::GetClassData() const {
  return CMsgGCItemCustomizationNotification_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
CMsgGCItemCustomizationNotification::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CMsgGCItemCustomizationNotification_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgGCItemCustomizationNotification>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint32 request = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_.request_)}},
    // repeated uint64 item_id = 1;
    {::_pbi::TcParser::FastV64R1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_.item_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint64 item_id = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_.item_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUInt64)},
    // optional uint32 request = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgGCItemCustomizationNotification, _impl_.request_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CMsgGCItemCustomizationNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGCItemCustomizationNotification)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.item_id_.Clear();
  }
  _impl_.request_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CMsgGCItemCustomizationNotification::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CMsgGCItemCustomizationNotification& this_ = static_cast<const CMsgGCItemCustomizationNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CMsgGCItemCustomizationNotification::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CMsgGCItemCustomizationNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGCItemCustomizationNotification)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated uint64 item_id = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_item_id_size(); i < n; ++i) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_item_id().Get(i), target);
    }
  }

  // optional uint32 request = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_request(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGCItemCustomizationNotification)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CMsgGCItemCustomizationNotification::ByteSizeLong(const MessageLite& base) {
  const CMsgGCItemCustomizationNotification& this_ = static_cast<const CMsgGCItemCustomizationNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CMsgGCItemCustomizationNotification::ByteSizeLong() const {
  const CMsgGCItemCustomizationNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CMsgGCItemCustomizationNotification)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated uint64 item_id = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::_pbi::WireFormatLite::UInt64Size(
          this_._internal_item_id());
      ::size_t tag_size = ::size_t{1} *
          ::_pbi::FromIntSize(this_._internal_item_id_size());
      total_size += tag_size + data_size;
    }
    // optional uint32 request = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_request());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CMsgGCItemCustomizationNotification::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CMsgGCItemCustomizationNotification*>(&to_msg);
  auto& from = static_cast<const CMsgGCItemCustomizationNotification&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGCItemCustomizationNotification)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_item_id()->MergeFrom(from._internal_item_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.request_ = from._impl_.request_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void CMsgGCItemCustomizationNotification::CopyFrom(const CMsgGCItemCustomizationNotification& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CMsgGCItemCustomizationNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgGCItemCustomizationNotification::InternalSwap(CMsgGCItemCustomizationNotification* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.item_id_.InternalSwap(&other->_impl_.item_id_);
  swap(_impl_.request_, other->_impl_.request_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
