// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: econ_gcmessages.proto
// Protobuf C++ Version: 7.34.1

#ifndef econ_5fgcmessages_2eproto_2epb_2eh
#define econ_5fgcmessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_econ_5fgcmessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_econ_5fgcmessages_2eproto {
  static const ::uint32_t offsets[];
};
enum EGCItemCustomizationNotification : int;
extern const uint32_t EGCItemCustomizationNotification_internal_data_[];
enum EGCItemMsg : int;
extern const uint32_t EGCItemMsg_internal_data_[];
enum EGCMsgResponse : int;
extern const uint32_t EGCMsgResponse_internal_data_[];
enum EUnlockStyle : int;
extern const uint32_t EUnlockStyle_internal_data_[];
class CMsgCasketItem;
struct CMsgCasketItemDefaultTypeInternal;
extern CMsgCasketItemDefaultTypeInternal _CMsgCasketItem_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> CMsgCasketItem_class_data_;
class CMsgGCGiftedItems;
struct CMsgGCGiftedItemsDefaultTypeInternal;
extern CMsgGCGiftedItemsDefaultTypeInternal _CMsgGCGiftedItems_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<18> CMsgGCGiftedItems_class_data_;
class CMsgGCItemCustomizationNotification;
struct CMsgGCItemCustomizationNotificationDefaultTypeInternal;
extern CMsgGCItemCustomizationNotificationDefaultTypeInternal _CMsgGCItemCustomizationNotification_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<36> CMsgGCItemCustomizationNotification_class_data_;
class CMsgGCUserTrackTimePlayedConsecutively;
struct CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal;
extern CMsgGCUserTrackTimePlayedConsecutivelyDefaultTypeInternal _CMsgGCUserTrackTimePlayedConsecutively_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<39> CMsgGCUserTrackTimePlayedConsecutively_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EGCItemCustomizationNotification_internal_data_>
    internal::EnumTraitsImpl::value<::EGCItemCustomizationNotification>;
template <>
internal::EnumTraitsT<::EGCItemMsg_internal_data_>
    internal::EnumTraitsImpl::value<::EGCItemMsg>;
template <>
internal::EnumTraitsT<::EGCMsgResponse_internal_data_>
    internal::EnumTraitsImpl::value<::EGCMsgResponse>;
template <>
internal::EnumTraitsT<::EUnlockStyle_internal_data_>
    internal::EnumTraitsImpl::value<::EUnlockStyle>;
}  // namespace protobuf
}  // namespace google

enum EGCItemMsg : int {
  k_EMsgGCBase = 1000,
  k_EMsgGCSetItemPosition = 1001,
  k_EMsgGCCraft = 1002,
  k_EMsgGCCraftResponse = 1003,
  k_EMsgGCDelete = 1004,
  k_EMsgGCVerifyCacheSubscription = 1005,
  k_EMsgGCNameItem = 1006,
  k_EMsgGCUnlockCrate = 1007,
  k_EMsgGCUnlockCrateResponse = 1008,
  k_EMsgGCPaintItem = 1009,
  k_EMsgGCPaintItemResponse = 1010,
  k_EMsgGCGoldenWrenchBroadcast = 1011,
  k_EMsgGCMOTDRequest = 1012,
  k_EMsgGCMOTDRequestResponse = 1013,
  k_EMsgGCAddItemToSocket_DEPRECATED = 1014,
  k_EMsgGCAddItemToSocketResponse_DEPRECATED = 1015,
  k_EMsgGCAddSocketToBaseItem_DEPRECATED = 1016,
  k_EMsgGCAddSocketToItem_DEPRECATED = 1017,
  k_EMsgGCAddSocketToItemResponse_DEPRECATED = 1018,
  k_EMsgGCNameBaseItem = 1019,
  k_EMsgGCNameBaseItemResponse = 1020,
  k_EMsgGCRemoveSocketItem_DEPRECATED = 1021,
  k_EMsgGCRemoveSocketItemResponse_DEPRECATED = 1022,
  k_EMsgGCCustomizeItemTexture = 1023,
  k_EMsgGCCustomizeItemTextureResponse = 1024,
  k_EMsgGCUseItemRequest = 1025,
  k_EMsgGCUseItemResponse = 1026,
  k_EMsgGCGiftedItems_DEPRECATED = 1027,
  k_EMsgGCRemoveItemName = 1030,
  k_EMsgGCRemoveItemPaint = 1031,
  k_EMsgGCGiftWrapItem = 1032,
  k_EMsgGCGiftWrapItemResponse = 1033,
  k_EMsgGCDeliverGift = 1034,
  k_EMsgGCDeliverGiftResponseGiver = 1035,
  k_EMsgGCDeliverGiftResponseReceiver = 1036,
  k_EMsgGCUnwrapGiftRequest = 1037,
  k_EMsgGCUnwrapGiftResponse = 1038,
  k_EMsgGCSetItemStyle = 1039,
  k_EMsgGCUsedClaimCodeItem = 1040,
  k_EMsgGCSortItems = 1041,
  k_EMsgGC_RevolvingLootList_DEPRECATED = 1042,
  k_EMsgGCLookupAccount = 1043,
  k_EMsgGCLookupAccountResponse = 1044,
  k_EMsgGCLookupAccountName = 1045,
  k_EMsgGCLookupAccountNameResponse = 1046,
  k_EMsgGCUpdateItemSchema = 1049,
  k_EMsgGCRemoveCustomTexture = 1051,
  k_EMsgGCRemoveCustomTextureResponse = 1052,
  k_EMsgGCRemoveMakersMark = 1053,
  k_EMsgGCRemoveMakersMarkResponse = 1054,
  k_EMsgGCRemoveUniqueCraftIndex = 1055,
  k_EMsgGCRemoveUniqueCraftIndexResponse = 1056,
  k_EMsgGCSaxxyBroadcast = 1057,
  k_EMsgGCBackpackSortFinished = 1058,
  k_EMsgGCAdjustItemEquippedState = 1059,
  k_EMsgGCCollectItem = 1061,
  k_EMsgGCItemAcknowledged__DEPRECATED = 1062,
  k_EMsgGC_ReportAbuse = 1065,
  k_EMsgGC_ReportAbuseResponse = 1066,
  k_EMsgGCNameItemNotification = 1068,
  k_EMsgGCApplyConsumableEffects = 1069,
  k_EMsgGCConsumableExhausted = 1070,
  k_EMsgGCShowItemsPickedUp = 1071,
  k_EMsgGCClientDisplayNotification = 1072,
  k_EMsgGCApplyStrangePart = 1073,
  k_EMsgGC_IncrementKillCountAttribute = 1074,
  k_EMsgGC_IncrementKillCountResponse = 1075,
  k_EMsgGCApplyPennantUpgrade = 1076,
  k_EMsgGCSetItemPositions = 1077,
  k_EMsgGCApplyEggEssence = 1078,
  k_EMsgGCNameEggEssenceResponse = 1079,
  k_EMsgGCPaintKitItem = 1080,
  k_EMsgGCPaintKitBaseItem = 1081,
  k_EMsgGCPaintKitItemResponse = 1082,
  k_EMsgGCGiftedItems = 1083,
  k_EMsgGCUnlockItemStyle = 1084,
  k_EMsgGCUnlockItemStyleResponse = 1085,
  k_EMsgGCApplySticker = 1086,
  k_EMsgGCItemAcknowledged = 1087,
  k_EMsgGCStatTrakSwap = 1088,
  k_EMsgGCUserTrackTimePlayedConsecutively = 1089,
  k_EMsgGCItemCustomizationNotification = 1090,
  k_EMsgGCModifyItemAttribute = 1091,
  k_EMsgGCCasketItemAdd = 1092,
  k_EMsgGCCasketItemExtract = 1093,
  k_EMsgGCCasketItemLoadContents = 1094,
  k_EMsgGCTradingBase = 1500,
  k_EMsgGCTrading_InitiateTradeRequest = 1501,
  k_EMsgGCTrading_InitiateTradeResponse = 1502,
  k_EMsgGCTrading_StartSession = 1503,
  k_EMsgGCTrading_SetItem = 1504,
  k_EMsgGCTrading_RemoveItem = 1505,
  k_EMsgGCTrading_UpdateTradeInfo = 1506,
  k_EMsgGCTrading_SetReadiness = 1507,
  k_EMsgGCTrading_ReadinessResponse = 1508,
  k_EMsgGCTrading_SessionClosed = 1509,
  k_EMsgGCTrading_CancelSession = 1510,
  k_EMsgGCTrading_TradeChatMsg = 1511,
  k_EMsgGCTrading_ConfirmOffer = 1512,
  k_EMsgGCTrading_TradeTypingChatMsg = 1513,
  k_EMsgGCServerBrowser_FavoriteServer = 1601,
  k_EMsgGCServerBrowser_BlacklistServer = 1602,
  k_EMsgGCServerRentalsBase = 1700,
  k_EMsgGCItemPreviewCheckStatus = 1701,
  k_EMsgGCItemPreviewStatusResponse = 1702,
  k_EMsgGCItemPreviewRequest = 1703,
  k_EMsgGCItemPreviewRequestResponse = 1704,
  k_EMsgGCItemPreviewExpire = 1705,
  k_EMsgGCItemPreviewExpireNotification = 1706,
  k_EMsgGCItemPreviewItemBoughtNotification = 1707,
  k_EMsgGCDev_NewItemRequest = 2001,
  k_EMsgGCDev_NewItemRequestResponse = 2002,
  k_EMsgGCDev_PaintKitDropItem = 2003,
  k_EMsgGCStoreGetUserData = 2500,
  k_EMsgGCStoreGetUserDataResponse = 2501,
  k_EMsgGCStorePurchaseInit_DEPRECATED = 2502,
  k_EMsgGCStorePurchaseInitResponse_DEPRECATED = 2503,
  k_EMsgGCStorePurchaseFinalize = 2504,
  k_EMsgGCStorePurchaseFinalizeResponse = 2505,
  k_EMsgGCStorePurchaseCancel = 2506,
  k_EMsgGCStorePurchaseCancelResponse = 2507,
  k_EMsgGCStorePurchaseQueryTxn = 2508,
  k_EMsgGCStorePurchaseQueryTxnResponse = 2509,
  k_EMsgGCStorePurchaseInit = 2510,
  k_EMsgGCStorePurchaseInitResponse = 2511,
  k_EMsgGCBannedWordListRequest = 2512,
  k_EMsgGCBannedWordListResponse = 2513,
  k_EMsgGCToGCBannedWordListBroadcast = 2514,
  k_EMsgGCToGCBannedWordListUpdated = 2515,
  k_EMsgGCToGCDirtySDOCache = 2516,
  k_EMsgGCToGCDirtyMultipleSDOCache = 2517,
  k_EMsgGCToGCUpdateSQLKeyValue = 2518,
  k_EMsgGCToGCIsTrustedServer = 2519,
  k_EMsgGCToGCIsTrustedServerResponse = 2520,
  k_EMsgGCToGCBroadcastConsoleCommand = 2521,
  k_EMsgGCServerVersionUpdated = 2522,
  k_EMsgGCToGCWebAPIAccountChanged = 2524,
  k_EMsgGCRequestAnnouncements = 2525,
  k_EMsgGCRequestAnnouncementsResponse = 2526,
  k_EMsgGCRequestPassportItemGrant = 2527,
  k_EMsgGCClientVersionUpdated = 2528,
  k_EMsgGCAdjustItemEquippedStateMulti = 2529,
  k_EMsgGCRecurringSubscriptionStatus = 2530,
  k_EMsgGCAdjustEquipSlots = 2531,
};

extern const uint32_t EGCItemMsg_internal_data_[];
inline constexpr EGCItemMsg EGCItemMsg_MIN =
    static_cast<EGCItemMsg>(1000);
inline constexpr EGCItemMsg EGCItemMsg_MAX =
    static_cast<EGCItemMsg>(2531);
[[nodiscard]] inline bool EGCItemMsg_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, EGCItemMsg_internal_data_);
}
inline constexpr int EGCItemMsg_ARRAYSIZE = 2531 + 1;
[[nodiscard]] const ::std::string& EGCItemMsg_Name(EGCItemMsg value);
template <typename T>
[[nodiscard]] const ::std::string& EGCItemMsg_Name(T value) {
  static_assert(::std::is_same<T, EGCItemMsg>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EGCItemMsg_Name().");
  return EGCItemMsg_Name(static_cast<EGCItemMsg>(value));
}
[[nodiscard]] bool EGCItemMsg_Parse(
    ::absl::string_view name, EGCItemMsg* PROTOBUF_NONNULL value);
enum EGCMsgResponse : int {
  k_EGCMsgResponseOK = 0,
  k_EGCMsgResponseDenied = 1,
  k_EGCMsgResponseServerError = 2,
  k_EGCMsgResponseTimeout = 3,
  k_EGCMsgResponseInvalid = 4,
  k_EGCMsgResponseNoMatch = 5,
  k_EGCMsgResponseUnknownError = 6,
  k_EGCMsgResponseNotLoggedOn = 7,
  k_EGCMsgFailedToCreate = 8,
  k_EGCMsgLimitExceeded = 9,
  k_EGCMsgCommitUnfinalized = 10,
};

extern const uint32_t EGCMsgResponse_internal_data_[];
inline constexpr EGCMsgResponse EGCMsgResponse_MIN =
    static_cast<EGCMsgResponse>(0);
inline constexpr EGCMsgResponse EGCMsgResponse_MAX =
    static_cast<EGCMsgResponse>(10);
[[nodiscard]] inline bool EGCMsgResponse_IsValid(int value) {
  return 0 <= value && value <= 10;
}
inline constexpr int EGCMsgResponse_ARRAYSIZE = 10 + 1;
[[nodiscard]] const ::std::string& EGCMsgResponse_Name(EGCMsgResponse value);
template <typename T>
[[nodiscard]] const ::std::string& EGCMsgResponse_Name(T value) {
  static_assert(::std::is_same<T, EGCMsgResponse>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EGCMsgResponse_Name().");
  return EGCMsgResponse_Name(static_cast<EGCMsgResponse>(value));
}
[[nodiscard]] bool EGCMsgResponse_Parse(
    ::absl::string_view name, EGCMsgResponse* PROTOBUF_NONNULL value);
enum EUnlockStyle : int {
  k_UnlockStyle_Succeeded = 0,
  k_UnlockStyle_Failed_PreReq = 1,
  k_UnlockStyle_Failed_CantAfford = 2,
  k_UnlockStyle_Failed_CantCommit = 3,
  k_UnlockStyle_Failed_CantLockCache = 4,
  k_UnlockStyle_Failed_CantAffordAttrib = 5,
};

extern const uint32_t EUnlockStyle_internal_data_[];
inline constexpr EUnlockStyle EUnlockStyle_MIN =
    static_cast<EUnlockStyle>(0);
inline constexpr EUnlockStyle EUnlockStyle_MAX =
    static_cast<EUnlockStyle>(5);
[[nodiscard]] inline bool EUnlockStyle_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int EUnlockStyle_ARRAYSIZE = 5 + 1;
[[nodiscard]] const ::std::string& EUnlockStyle_Name(EUnlockStyle value);
template <typename T>
[[nodiscard]] const ::std::string& EUnlockStyle_Name(T value) {
  static_assert(::std::is_same<T, EUnlockStyle>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EUnlockStyle_Name().");
  return EUnlockStyle_Name(static_cast<EUnlockStyle>(value));
}
[[nodiscard]] bool EUnlockStyle_Parse(
    ::absl::string_view name, EUnlockStyle* PROTOBUF_NONNULL value);
enum EGCItemCustomizationNotification : int {
  k_EGCItemCustomizationNotification_NameItem = 1006,
  k_EGCItemCustomizationNotification_UnlockCrate = 1007,
  k_EGCItemCustomizationNotification_XRayItemReveal = 1008,
  k_EGCItemCustomizationNotification_XRayItemClaim = 1009,
  k_EGCItemCustomizationNotification_CasketTooFull = 1011,
  k_EGCItemCustomizationNotification_CasketContents = 1012,
  k_EGCItemCustomizationNotification_CasketAdded = 1013,
  k_EGCItemCustomizationNotification_CasketRemoved = 1014,
  k_EGCItemCustomizationNotification_CasketInvFull = 1015,
  k_EGCItemCustomizationNotification_NameBaseItem = 1019,
  k_EGCItemCustomizationNotification_RemoveItemName = 1030,
  k_EGCItemCustomizationNotification_RemoveSticker = 1053,
  k_EGCItemCustomizationNotification_ApplySticker = 1086,
  k_EGCItemCustomizationNotification_StatTrakSwap = 1088,
  k_EGCItemCustomizationNotification_RemovePatch = 1089,
  k_EGCItemCustomizationNotification_ApplyPatch = 1090,
  k_EGCItemCustomizationNotification_ActivateFanToken = 9178,
  k_EGCItemCustomizationNotification_ActivateOperationCoin = 9179,
  k_EGCItemCustomizationNotification_GraffitiUnseal = 9185,
  k_EGCItemCustomizationNotification_GenerateSouvenir = 9204,
  k_EGCItemCustomizationNotification_ClientRedeemMissionReward = 9209,
};

extern const uint32_t EGCItemCustomizationNotification_internal_data_[];
inline constexpr EGCItemCustomizationNotification EGCItemCustomizationNotification_MIN =
    static_cast<EGCItemCustomizationNotification>(1006);
inline constexpr EGCItemCustomizationNotification EGCItemCustomizationNotification_MAX =
    static_cast<EGCItemCustomizationNotification>(9209);
[[nodiscard]] inline bool EGCItemCustomizationNotification_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, EGCItemCustomizationNotification_internal_data_);
}
inline constexpr int EGCItemCustomizationNotification_ARRAYSIZE = 9209 + 1;
[[nodiscard]] const ::std::string& EGCItemCustomizationNotification_Name(EGCItemCustomizationNotification value);
template <typename T>
[[nodiscard]] const ::std::string& EGCItemCustomizationNotification_Name(T value) {
  static_assert(::std::is_same<T, EGCItemCustomizationNotification>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EGCItemCustomizationNotification_Name().");
  return EGCItemCustomizationNotification_Name(static_cast<EGCItemCustomizationNotification>(value));
}
[[nodiscard]] bool EGCItemCustomizationNotification_Parse(
    ::absl::string_view name, EGCItemCustomizationNotification* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CMsgGCUserTrackTimePlayedConsecutively final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:CMsgGCUserTrackTimePlayedConsecutively) */ {
 public:
  inline CMsgGCUserTrackTimePlayedConsecutively() : CMsgGCUserTrackTimePlayedConsecutively(nullptr) {}
  ~CMsgGCUserTrackTimePlayedConsecutively() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgGCUserTrackTimePlayedConsecutively* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgGCUserTrackTimePlayedConsecutively));
  }
#endif

  template <typename = void>
  explicit constexpr CMsgGCUserTrackTimePlayedConsecutively(::google::protobuf::internal::ConstantInitialized);

  inline CMsgGCUserTrackTimePlayedConsecutively(const CMsgGCUserTrackTimePlayedConsecutively& from) : CMsgGCUserTrackTimePlayedConsecutively(nullptr, from) {}
  inline CMsgGCUserTrackTimePlayedConsecutively(CMsgGCUserTrackTimePlayedConsecutively&& from) noexcept
      : CMsgGCUserTrackTimePlayedConsecutively(nullptr, ::std::move(from)) {}
  inline CMsgGCUserTrackTimePlayedConsecutively& operator=(const CMsgGCUserTrackTimePlayedConsecutively& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCUserTrackTimePlayedConsecutively& operator=(CMsgGCUserTrackTimePlayedConsecutively&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const CMsgGCUserTrackTimePlayedConsecutively& default_instance() {
    return *reinterpret_cast<const CMsgGCUserTrackTimePlayedConsecutively*>(
        &_CMsgGCUserTrackTimePlayedConsecutively_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CMsgGCUserTrackTimePlayedConsecutively& a, CMsgGCUserTrackTimePlayedConsecutively& b) { a.Swap(&b); }
  inline void Swap(CMsgGCUserTrackTimePlayedConsecutively* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCUserTrackTimePlayedConsecutively* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CMsgGCUserTrackTimePlayedConsecutively* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<CMsgGCUserTrackTimePlayedConsecutively>(arena);
  }
  void CopyFrom(const CMsgGCUserTrackTimePlayedConsecutively& from);
  void MergeFrom(const CMsgGCUserTrackTimePlayedConsecutively& from) { CMsgGCUserTrackTimePlayedConsecutively::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgGCUserTrackTimePlayedConsecutively* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgGCUserTrackTimePlayedConsecutively"; }

  explicit CMsgGCUserTrackTimePlayedConsecutively(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgGCUserTrackTimePlayedConsecutively(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgGCUserTrackTimePlayedConsecutively& from);
  CMsgGCUserTrackTimePlayedConsecutively(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgGCUserTrackTimePlayedConsecutively&& from) noexcept
      : CMsgGCUserTrackTimePlayedConsecutively(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStateFieldNumber = 1,
  };
  // optional uint32 state = 1;
  [[nodiscard]] bool has_state()
      const;
  void clear_state() ;
  [[nodiscard]] ::uint32_t state() const;
  void set_state(::uint32_t value);

  private:
  ::uint32_t _internal_state() const;
  void _internal_set_state(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgGCUserTrackTimePlayedConsecutively)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgGCUserTrackTimePlayedConsecutively& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t state_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<39> CMsgGCUserTrackTimePlayedConsecutively_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CMsgGCItemCustomizationNotification final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:CMsgGCItemCustomizationNotification) */ {
 public:
  inline CMsgGCItemCustomizationNotification() : CMsgGCItemCustomizationNotification(nullptr) {}
  ~CMsgGCItemCustomizationNotification() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgGCItemCustomizationNotification* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgGCItemCustomizationNotification));
  }
#endif

  template <typename = void>
  explicit constexpr CMsgGCItemCustomizationNotification(::google::protobuf::internal::ConstantInitialized);

  inline CMsgGCItemCustomizationNotification(const CMsgGCItemCustomizationNotification& from) : CMsgGCItemCustomizationNotification(nullptr, from) {}
  inline CMsgGCItemCustomizationNotification(CMsgGCItemCustomizationNotification&& from) noexcept
      : CMsgGCItemCustomizationNotification(nullptr, ::std::move(from)) {}
  inline CMsgGCItemCustomizationNotification& operator=(const CMsgGCItemCustomizationNotification& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCItemCustomizationNotification& operator=(CMsgGCItemCustomizationNotification&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const CMsgGCItemCustomizationNotification& default_instance() {
    return *reinterpret_cast<const CMsgGCItemCustomizationNotification*>(
        &_CMsgGCItemCustomizationNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(CMsgGCItemCustomizationNotification& a, CMsgGCItemCustomizationNotification& b) { a.Swap(&b); }
  inline void Swap(CMsgGCItemCustomizationNotification* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCItemCustomizationNotification* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CMsgGCItemCustomizationNotification* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<CMsgGCItemCustomizationNotification>(arena);
  }
  void CopyFrom(const CMsgGCItemCustomizationNotification& from);
  void MergeFrom(const CMsgGCItemCustomizationNotification& from) { CMsgGCItemCustomizationNotification::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgGCItemCustomizationNotification* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgGCItemCustomizationNotification"; }

  explicit CMsgGCItemCustomizationNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgGCItemCustomizationNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgGCItemCustomizationNotification& from);
  CMsgGCItemCustomizationNotification(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgGCItemCustomizationNotification&& from) noexcept
      : CMsgGCItemCustomizationNotification(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemIdFieldNumber = 1,
    kRequestFieldNumber = 2,
  };
  // repeated uint64 item_id = 1;
  [[nodiscard]] int item_id_size()
      const;
  private:
  int _internal_item_id_size() const;

  public:
  void clear_item_id() ;
  [[nodiscard]] ::uint64_t item_id(int index) const;
  void set_item_id(int index, ::uint64_t value);
  void add_item_id(::uint64_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::uint64_t>& item_id() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL mutable_item_id();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_item_id() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL _internal_mutable_item_id();

  public:
  // optional uint32 request = 2;
  [[nodiscard]] bool has_request()
      const;
  void clear_request() ;
  [[nodiscard]] ::uint32_t request() const;
  void set_request(::uint32_t value);

  private:
  ::uint32_t _internal_request() const;
  void _internal_set_request(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgGCItemCustomizationNotification)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgGCItemCustomizationNotification& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint64_t> item_id_;
    ::uint32_t request_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<36> CMsgGCItemCustomizationNotification_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CMsgGCGiftedItems final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:CMsgGCGiftedItems) */ {
 public:
  inline CMsgGCGiftedItems() : CMsgGCGiftedItems(nullptr) {}
  ~CMsgGCGiftedItems() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgGCGiftedItems* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgGCGiftedItems));
  }
#endif

  template <typename = void>
  explicit constexpr CMsgGCGiftedItems(::google::protobuf::internal::ConstantInitialized);

  inline CMsgGCGiftedItems(const CMsgGCGiftedItems& from) : CMsgGCGiftedItems(nullptr, from) {}
  inline CMsgGCGiftedItems(CMsgGCGiftedItems&& from) noexcept
      : CMsgGCGiftedItems(nullptr, ::std::move(from)) {}
  inline CMsgGCGiftedItems& operator=(const CMsgGCGiftedItems& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgGCGiftedItems& operator=(CMsgGCGiftedItems&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const CMsgGCGiftedItems& default_instance() {
    return *reinterpret_cast<const CMsgGCGiftedItems*>(
        &_CMsgGCGiftedItems_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CMsgGCGiftedItems& a, CMsgGCGiftedItems& b) { a.Swap(&b); }
  inline void Swap(CMsgGCGiftedItems* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgGCGiftedItems* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CMsgGCGiftedItems* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<CMsgGCGiftedItems>(arena);
  }
  void CopyFrom(const CMsgGCGiftedItems& from);
  void MergeFrom(const CMsgGCGiftedItems& from) { CMsgGCGiftedItems::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgGCGiftedItems* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgGCGiftedItems"; }

  explicit CMsgGCGiftedItems(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgGCGiftedItems(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgGCGiftedItems& from);
  CMsgGCGiftedItems(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgGCGiftedItems&& from) noexcept
      : CMsgGCGiftedItems(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRecipientsAccountidsFieldNumber = 5,
    kAccountidFieldNumber = 1,
    kGiftdefindexFieldNumber = 2,
    kMaxGiftsPossibleFieldNumber = 3,
    kNumEligibleRecipientsFieldNumber = 4,
  };
  // repeated uint32 recipients_accountids = 5;
  [[nodiscard]] int recipients_accountids_size()
      const;
  private:
  int _internal_recipients_accountids_size() const;

  public:
  void clear_recipients_accountids() ;
  [[nodiscard]] ::uint32_t recipients_accountids(int index) const;
  void set_recipients_accountids(int index, ::uint32_t value);
  void add_recipients_accountids(::uint32_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::uint32_t>& recipients_accountids() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_recipients_accountids();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_recipients_accountids() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_recipients_accountids();

  public:
  // optional uint32 accountid = 1;
  [[nodiscard]] bool has_accountid()
      const;
  void clear_accountid() ;
  [[nodiscard]] ::uint32_t accountid() const;
  void set_accountid(::uint32_t value);

  private:
  ::uint32_t _internal_accountid() const;
  void _internal_set_accountid(::uint32_t value);

  public:
  // optional uint32 giftdefindex = 2;
  [[nodiscard]] bool has_giftdefindex()
      const;
  void clear_giftdefindex() ;
  [[nodiscard]] ::uint32_t giftdefindex() const;
  void set_giftdefindex(::uint32_t value);

  private:
  ::uint32_t _internal_giftdefindex() const;
  void _internal_set_giftdefindex(::uint32_t value);

  public:
  // optional uint32 max_gifts_possible = 3;
  [[nodiscard]] bool has_max_gifts_possible()
      const;
  void clear_max_gifts_possible() ;
  [[nodiscard]] ::uint32_t max_gifts_possible() const;
  void set_max_gifts_possible(::uint32_t value);

  private:
  ::uint32_t _internal_max_gifts_possible() const;
  void _internal_set_max_gifts_possible(::uint32_t value);

  public:
  // optional uint32 num_eligible_recipients = 4;
  [[nodiscard]] bool has_num_eligible_recipients()
      const;
  void clear_num_eligible_recipients() ;
  [[nodiscard]] ::uint32_t num_eligible_recipients() const;
  void set_num_eligible_recipients(::uint32_t value);

  private:
  ::uint32_t _internal_num_eligible_recipients() const;
  void _internal_set_num_eligible_recipients(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgGCGiftedItems)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgGCGiftedItems& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> recipients_accountids_;
    ::uint32_t accountid_;
    ::uint32_t giftdefindex_;
    ::uint32_t max_gifts_possible_;
    ::uint32_t num_eligible_recipients_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<18> CMsgGCGiftedItems_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CMsgCasketItem final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:CMsgCasketItem) */ {
 public:
  inline CMsgCasketItem() : CMsgCasketItem(nullptr) {}
  ~CMsgCasketItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgCasketItem* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgCasketItem));
  }
#endif

  template <typename = void>
  explicit constexpr CMsgCasketItem(::google::protobuf::internal::ConstantInitialized);

  inline CMsgCasketItem(const CMsgCasketItem& from) : CMsgCasketItem(nullptr, from) {}
  inline CMsgCasketItem(CMsgCasketItem&& from) noexcept
      : CMsgCasketItem(nullptr, ::std::move(from)) {}
  inline CMsgCasketItem& operator=(const CMsgCasketItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgCasketItem& operator=(CMsgCasketItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const CMsgCasketItem& default_instance() {
    return *reinterpret_cast<const CMsgCasketItem*>(
        &_CMsgCasketItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CMsgCasketItem& a, CMsgCasketItem& b) { a.Swap(&b); }
  inline void Swap(CMsgCasketItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgCasketItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CMsgCasketItem* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<CMsgCasketItem>(arena);
  }
  void CopyFrom(const CMsgCasketItem& from);
  void MergeFrom(const CMsgCasketItem& from) { CMsgCasketItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgCasketItem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgCasketItem"; }

  explicit CMsgCasketItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgCasketItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgCasketItem& from);
  CMsgCasketItem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgCasketItem&& from) noexcept
      : CMsgCasketItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCasketItemIdFieldNumber = 1,
    kItemItemIdFieldNumber = 2,
  };
  // optional uint64 casket_item_id = 1;
  [[nodiscard]] bool has_casket_item_id()
      const;
  void clear_casket_item_id() ;
  [[nodiscard]] ::uint64_t casket_item_id() const;
  void set_casket_item_id(::uint64_t value);

  private:
  ::uint64_t _internal_casket_item_id() const;
  void _internal_set_casket_item_id(::uint64_t value);

  public:
  // optional uint64 item_item_id = 2;
  [[nodiscard]] bool has_item_item_id()
      const;
  void clear_item_item_id() ;
  [[nodiscard]] ::uint64_t item_item_id() const;
  void set_item_item_id(::uint64_t value);

  private:
  ::uint64_t _internal_item_item_id() const;
  void _internal_set_item_item_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgCasketItem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgCasketItem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t casket_item_id_;
    ::uint64_t item_item_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_econ_5fgcmessages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> CMsgCasketItem_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CMsgGCGiftedItems

// optional uint32 accountid = 1;
inline bool CMsgGCGiftedItems::has_accountid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgGCGiftedItems::clear_accountid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accountid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CMsgGCGiftedItems::accountid() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.accountid)
  return _internal_accountid();
}
inline void CMsgGCGiftedItems::set_accountid(::uint32_t value) {
  _internal_set_accountid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.accountid)
}
inline ::uint32_t CMsgGCGiftedItems::_internal_accountid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accountid_;
}
inline void CMsgGCGiftedItems::_internal_set_accountid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accountid_ = value;
}

// optional uint32 giftdefindex = 2;
inline bool CMsgGCGiftedItems::has_giftdefindex() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CMsgGCGiftedItems::clear_giftdefindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.giftdefindex_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t CMsgGCGiftedItems::giftdefindex() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.giftdefindex)
  return _internal_giftdefindex();
}
inline void CMsgGCGiftedItems::set_giftdefindex(::uint32_t value) {
  _internal_set_giftdefindex(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.giftdefindex)
}
inline ::uint32_t CMsgGCGiftedItems::_internal_giftdefindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.giftdefindex_;
}
inline void CMsgGCGiftedItems::_internal_set_giftdefindex(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.giftdefindex_ = value;
}

// optional uint32 max_gifts_possible = 3;
inline bool CMsgGCGiftedItems::has_max_gifts_possible() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CMsgGCGiftedItems::clear_max_gifts_possible() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_gifts_possible_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t CMsgGCGiftedItems::max_gifts_possible() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.max_gifts_possible)
  return _internal_max_gifts_possible();
}
inline void CMsgGCGiftedItems::set_max_gifts_possible(::uint32_t value) {
  _internal_set_max_gifts_possible(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.max_gifts_possible)
}
inline ::uint32_t CMsgGCGiftedItems::_internal_max_gifts_possible() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_gifts_possible_;
}
inline void CMsgGCGiftedItems::_internal_set_max_gifts_possible(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_gifts_possible_ = value;
}

// optional uint32 num_eligible_recipients = 4;
inline bool CMsgGCGiftedItems::has_num_eligible_recipients() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CMsgGCGiftedItems::clear_num_eligible_recipients() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_eligible_recipients_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t CMsgGCGiftedItems::num_eligible_recipients() const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.num_eligible_recipients)
  return _internal_num_eligible_recipients();
}
inline void CMsgGCGiftedItems::set_num_eligible_recipients(::uint32_t value) {
  _internal_set_num_eligible_recipients(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.num_eligible_recipients)
}
inline ::uint32_t CMsgGCGiftedItems::_internal_num_eligible_recipients() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_eligible_recipients_;
}
inline void CMsgGCGiftedItems::_internal_set_num_eligible_recipients(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_eligible_recipients_ = value;
}

// repeated uint32 recipients_accountids = 5;
inline int CMsgGCGiftedItems::_internal_recipients_accountids_size() const {
  return _internal_recipients_accountids().size();
}
inline int CMsgGCGiftedItems::recipients_accountids_size() const {
  return _internal_recipients_accountids_size();
}
inline void CMsgGCGiftedItems::clear_recipients_accountids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recipients_accountids_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t CMsgGCGiftedItems::recipients_accountids(int index) const {
  // @@protoc_insertion_point(field_get:CMsgGCGiftedItems.recipients_accountids)
  return _internal_recipients_accountids().Get(index);
}
inline void CMsgGCGiftedItems::set_recipients_accountids(int index, ::uint32_t value) {
  _internal_mutable_recipients_accountids()->Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgGCGiftedItems.recipients_accountids)
}
inline void CMsgGCGiftedItems::add_recipients_accountids(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_recipients_accountids()->InternalAddWithArena(
      internal_visibility(), GetArena(), value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:CMsgGCGiftedItems.recipients_accountids)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& CMsgGCGiftedItems::recipients_accountids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:CMsgGCGiftedItems.recipients_accountids)
  return _internal_recipients_accountids();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL CMsgGCGiftedItems::mutable_recipients_accountids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:CMsgGCGiftedItems.recipients_accountids)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_recipients_accountids();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
CMsgGCGiftedItems::_internal_recipients_accountids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.recipients_accountids_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
CMsgGCGiftedItems::_internal_mutable_recipients_accountids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.recipients_accountids_;
}

// -------------------------------------------------------------------

// CMsgCasketItem

// optional uint64 casket_item_id = 1;
inline bool CMsgCasketItem::has_casket_item_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgCasketItem::clear_casket_item_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.casket_item_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t CMsgCasketItem::casket_item_id() const {
  // @@protoc_insertion_point(field_get:CMsgCasketItem.casket_item_id)
  return _internal_casket_item_id();
}
inline void CMsgCasketItem::set_casket_item_id(::uint64_t value) {
  _internal_set_casket_item_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CMsgCasketItem.casket_item_id)
}
inline ::uint64_t CMsgCasketItem::_internal_casket_item_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.casket_item_id_;
}
inline void CMsgCasketItem::_internal_set_casket_item_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.casket_item_id_ = value;
}

// optional uint64 item_item_id = 2;
inline bool CMsgCasketItem::has_item_item_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgCasketItem::clear_item_item_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_item_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t CMsgCasketItem::item_item_id() const {
  // @@protoc_insertion_point(field_get:CMsgCasketItem.item_item_id)
  return _internal_item_item_id();
}
inline void CMsgCasketItem::set_item_item_id(::uint64_t value) {
  _internal_set_item_item_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgCasketItem.item_item_id)
}
inline ::uint64_t CMsgCasketItem::_internal_item_item_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_item_id_;
}
inline void CMsgCasketItem::_internal_set_item_item_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_item_id_ = value;
}

// -------------------------------------------------------------------

// CMsgGCUserTrackTimePlayedConsecutively

// optional uint32 state = 1;
inline bool CMsgGCUserTrackTimePlayedConsecutively::has_state() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgGCUserTrackTimePlayedConsecutively::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t CMsgGCUserTrackTimePlayedConsecutively::state() const {
  // @@protoc_insertion_point(field_get:CMsgGCUserTrackTimePlayedConsecutively.state)
  return _internal_state();
}
inline void CMsgGCUserTrackTimePlayedConsecutively::set_state(::uint32_t value) {
  _internal_set_state(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CMsgGCUserTrackTimePlayedConsecutively.state)
}
inline ::uint32_t CMsgGCUserTrackTimePlayedConsecutively::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_;
}
inline void CMsgGCUserTrackTimePlayedConsecutively::_internal_set_state(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// -------------------------------------------------------------------

// CMsgGCItemCustomizationNotification

// repeated uint64 item_id = 1;
inline int CMsgGCItemCustomizationNotification::_internal_item_id_size() const {
  return _internal_item_id().size();
}
inline int CMsgGCItemCustomizationNotification::item_id_size() const {
  return _internal_item_id_size();
}
inline void CMsgGCItemCustomizationNotification::clear_item_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t CMsgGCItemCustomizationNotification::item_id(int index) const {
  // @@protoc_insertion_point(field_get:CMsgGCItemCustomizationNotification.item_id)
  return _internal_item_id().Get(index);
}
inline void CMsgGCItemCustomizationNotification::set_item_id(int index, ::uint64_t value) {
  _internal_mutable_item_id()->Set(index, value);
  // @@protoc_insertion_point(field_set:CMsgGCItemCustomizationNotification.item_id)
}
inline void CMsgGCItemCustomizationNotification::add_item_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_item_id()->InternalAddWithArena(
      internal_visibility(), GetArena(), value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:CMsgGCItemCustomizationNotification.item_id)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& CMsgGCItemCustomizationNotification::item_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:CMsgGCItemCustomizationNotification.item_id)
  return _internal_item_id();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL CMsgGCItemCustomizationNotification::mutable_item_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:CMsgGCItemCustomizationNotification.item_id)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_item_id();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
CMsgGCItemCustomizationNotification::_internal_item_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_id_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL
CMsgGCItemCustomizationNotification::_internal_mutable_item_id() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.item_id_;
}

// optional uint32 request = 2;
inline bool CMsgGCItemCustomizationNotification::has_request() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgGCItemCustomizationNotification::clear_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CMsgGCItemCustomizationNotification::request() const {
  // @@protoc_insertion_point(field_get:CMsgGCItemCustomizationNotification.request)
  return _internal_request();
}
inline void CMsgGCItemCustomizationNotification::set_request(::uint32_t value) {
  _internal_set_request(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgGCItemCustomizationNotification.request)
}
inline ::uint32_t CMsgGCItemCustomizationNotification::_internal_request() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.request_;
}
inline void CMsgGCItemCustomizationNotification::_internal_set_request(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.request_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EGCItemMsg> : std::true_type {};
template <>
struct is_proto_enum<::EGCMsgResponse> : std::true_type {};
template <>
struct is_proto_enum<::EUnlockStyle> : std::true_type {};
template <>
struct is_proto_enum<::EGCItemCustomizationNotification> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // econ_5fgcmessages_2eproto_2epb_2eh
