// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: engine_gcmessages.proto
// Protobuf C++ Version: 7.34.1

#include "engine_gcmessages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CEngineGotvSyncPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        match_id_{::uint64_t{0u}},
        instance_id_{0u},
        signupfragment_{0u},
        currentfragment_{0u},
        tickrate_{0},
        tick_{0u},
        rtdelay_{0},
        rcvage_{0},
        keyframe_interval_{0},
        cdndelay_{0u} {}

template <typename>
constexpr CEngineGotvSyncPacket::CEngineGotvSyncPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(CEngineGotvSyncPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CEngineGotvSyncPacketDefaultTypeInternal {
  constexpr CEngineGotvSyncPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CEngineGotvSyncPacketDefaultTypeInternal() {}
  union {
    CEngineGotvSyncPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CEngineGotvSyncPacketDefaultTypeInternal _CEngineGotvSyncPacket_default_instance_;
// ===================================================================

class CEngineGotvSyncPacket::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CEngineGotvSyncPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_._has_bits_);
};

CEngineGotvSyncPacket::CEngineGotvSyncPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CEngineGotvSyncPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CEngineGotvSyncPacket)
}
CEngineGotvSyncPacket::CEngineGotvSyncPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CEngineGotvSyncPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, CEngineGotvSyncPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CEngineGotvSyncPacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CEngineGotvSyncPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, match_id_),
           0,
           offsetof(Impl_, cdndelay_) -
               offsetof(Impl_, match_id_) +
               sizeof(Impl_::cdndelay_));
}
CEngineGotvSyncPacket::~CEngineGotvSyncPacket() {
  // @@protoc_insertion_point(destructor:CEngineGotvSyncPacket)
  SharedDtor(*this);
}
inline void CEngineGotvSyncPacket::SharedDtor(MessageLite& self) {
  CEngineGotvSyncPacket& this_ = static_cast<CEngineGotvSyncPacket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CEngineGotvSyncPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CEngineGotvSyncPacket(arena);
}
constexpr auto CEngineGotvSyncPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CEngineGotvSyncPacket),
                                            alignof(CEngineGotvSyncPacket));
}
constexpr auto CEngineGotvSyncPacket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<22>{
      {
          &_CEngineGotvSyncPacket_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CEngineGotvSyncPacket::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<CEngineGotvSyncPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CEngineGotvSyncPacket::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<CEngineGotvSyncPacket>(), &CEngineGotvSyncPacket::ByteSizeLong,
              &CEngineGotvSyncPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_._cached_size_),
          true,
      },
      "CEngineGotvSyncPacket",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<22> CEngineGotvSyncPacket_class_data_ =
    CEngineGotvSyncPacket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CEngineGotvSyncPacket::GetClassData() const {
  return CEngineGotvSyncPacket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 0, 2>
CEngineGotvSyncPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965312,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CEngineGotvSyncPacket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CEngineGotvSyncPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint64 match_id = 1;
    {::_pbi::TcParser::FastV64S1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.match_id_)}},
    // optional uint32 instance_id = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.instance_id_)}},
    // optional uint32 signupfragment = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.signupfragment_)}},
    // optional uint32 currentfragment = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.currentfragment_)}},
    // optional float tickrate = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 4, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tickrate_)}},
    // optional uint32 tick = 6;
    {::_pbi::TcParser::FastV32S1,
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tick_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional float rtdelay = 8;
    {::_pbi::TcParser::FastF32S1,
     {69, 6, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rtdelay_)}},
    // optional float rcvage = 9;
    {::_pbi::TcParser::FastF32S1,
     {77, 7, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rcvage_)}},
    // optional float keyframe_interval = 10;
    {::_pbi::TcParser::FastF32S1,
     {85, 8, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.keyframe_interval_)}},
    // optional uint32 cdndelay = 11;
    {::_pbi::TcParser::FastV32S1,
     {88, 9, 0,
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.cdndelay_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 match_id = 1;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.match_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint32 instance_id = 2;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.instance_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 signupfragment = 3;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.signupfragment_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 currentfragment = 4;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.currentfragment_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional float tickrate = 5;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tickrate_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional uint32 tick = 6;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.tick_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional float rtdelay = 8;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rtdelay_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float rcvage = 9;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.rcvage_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float keyframe_interval = 10;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.keyframe_interval_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional uint32 cdndelay = 11;
    {PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.cdndelay_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CEngineGotvSyncPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:CEngineGotvSyncPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    ::memset(&_impl_.match_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.rcvage_) -
        reinterpret_cast<char*>(&_impl_.match_id_)) + sizeof(_impl_.rcvage_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    ::memset(&_impl_.keyframe_interval_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.cdndelay_) -
        reinterpret_cast<char*>(&_impl_.keyframe_interval_)) + sizeof(_impl_.cdndelay_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CEngineGotvSyncPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CEngineGotvSyncPacket& this_ = static_cast<const CEngineGotvSyncPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CEngineGotvSyncPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CEngineGotvSyncPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CEngineGotvSyncPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 match_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_match_id(), target);
  }

  // optional uint32 instance_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_instance_id(), target);
  }

  // optional uint32 signupfragment = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_signupfragment(), target);
  }

  // optional uint32 currentfragment = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_currentfragment(), target);
  }

  // optional float tickrate = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this_._internal_tickrate(), target);
  }

  // optional uint32 tick = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_tick(), target);
  }

  // optional float rtdelay = 8;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this_._internal_rtdelay(), target);
  }

  // optional float rcvage = 9;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        9, this_._internal_rcvage(), target);
  }

  // optional float keyframe_interval = 10;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        10, this_._internal_keyframe_interval(), target);
  }

  // optional uint32 cdndelay = 11;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        11, this_._internal_cdndelay(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CEngineGotvSyncPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CEngineGotvSyncPacket::ByteSizeLong(const MessageLite& base) {
  const CEngineGotvSyncPacket& this_ = static_cast<const CEngineGotvSyncPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CEngineGotvSyncPacket::ByteSizeLong() const {
  const CEngineGotvSyncPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CEngineGotvSyncPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x000001d0U & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x0000002fU)) {
    // optional uint64 match_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_match_id());
    }
    // optional uint32 instance_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_instance_id());
    }
    // optional uint32 signupfragment = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_signupfragment());
    }
    // optional uint32 currentfragment = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_currentfragment());
    }
    // optional uint32 tick = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_tick());
    }
  }
   {
    // optional uint32 cdndelay = 11;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_cdndelay());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void CEngineGotvSyncPacket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CEngineGotvSyncPacket*>(&to_msg);
  auto& from = static_cast<const CEngineGotvSyncPacket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CEngineGotvSyncPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.match_id_ = from._impl_.match_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.instance_id_ = from._impl_.instance_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.signupfragment_ = from._impl_.signupfragment_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.currentfragment_ = from._impl_.currentfragment_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.tickrate_ = from._impl_.tickrate_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.tick_ = from._impl_.tick_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.rtdelay_ = from._impl_.rtdelay_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.rcvage_ = from._impl_.rcvage_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.keyframe_interval_ = from._impl_.keyframe_interval_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.cdndelay_ = from._impl_.cdndelay_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void CEngineGotvSyncPacket::CopyFrom(const CEngineGotvSyncPacket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CEngineGotvSyncPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CEngineGotvSyncPacket::InternalSwap(CEngineGotvSyncPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.cdndelay_)
      + sizeof(CEngineGotvSyncPacket::_impl_.cdndelay_)
      - PROTOBUF_FIELD_OFFSET(CEngineGotvSyncPacket, _impl_.match_id_)>(
          reinterpret_cast<char*>(&_impl_.match_id_),
          reinterpret_cast<char*>(&other->_impl_.match_id_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
