// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: engine_gcmessages.proto
// Protobuf C++ Version: 7.34.1

#ifndef engine_5fgcmessages_2eproto_2epb_2eh
#define engine_5fgcmessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_engine_5fgcmessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_engine_5fgcmessages_2eproto {
  static const ::uint32_t offsets[];
};
class CEngineGotvSyncPacket;
struct CEngineGotvSyncPacketDefaultTypeInternal;
extern CEngineGotvSyncPacketDefaultTypeInternal _CEngineGotvSyncPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<22> CEngineGotvSyncPacket_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CEngineGotvSyncPacket final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:CEngineGotvSyncPacket) */ {
 public:
  inline CEngineGotvSyncPacket() : CEngineGotvSyncPacket(nullptr) {}
  ~CEngineGotvSyncPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CEngineGotvSyncPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CEngineGotvSyncPacket));
  }
#endif

  template <typename = void>
  explicit constexpr CEngineGotvSyncPacket(::google::protobuf::internal::ConstantInitialized);

  inline CEngineGotvSyncPacket(const CEngineGotvSyncPacket& from) : CEngineGotvSyncPacket(nullptr, from) {}
  inline CEngineGotvSyncPacket(CEngineGotvSyncPacket&& from) noexcept
      : CEngineGotvSyncPacket(nullptr, ::std::move(from)) {}
  inline CEngineGotvSyncPacket& operator=(const CEngineGotvSyncPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline CEngineGotvSyncPacket& operator=(CEngineGotvSyncPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const CEngineGotvSyncPacket& default_instance() {
    return *reinterpret_cast<const CEngineGotvSyncPacket*>(
        &_CEngineGotvSyncPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CEngineGotvSyncPacket& a, CEngineGotvSyncPacket& b) { a.Swap(&b); }
  inline void Swap(CEngineGotvSyncPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CEngineGotvSyncPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CEngineGotvSyncPacket* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<CEngineGotvSyncPacket>(arena);
  }
  void CopyFrom(const CEngineGotvSyncPacket& from);
  void MergeFrom(const CEngineGotvSyncPacket& from) { CEngineGotvSyncPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CEngineGotvSyncPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CEngineGotvSyncPacket"; }

  explicit CEngineGotvSyncPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CEngineGotvSyncPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CEngineGotvSyncPacket& from);
  CEngineGotvSyncPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CEngineGotvSyncPacket&& from) noexcept
      : CEngineGotvSyncPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMatchIdFieldNumber = 1,
    kInstanceIdFieldNumber = 2,
    kSignupfragmentFieldNumber = 3,
    kCurrentfragmentFieldNumber = 4,
    kTickrateFieldNumber = 5,
    kTickFieldNumber = 6,
    kRtdelayFieldNumber = 8,
    kRcvageFieldNumber = 9,
    kKeyframeIntervalFieldNumber = 10,
    kCdndelayFieldNumber = 11,
  };
  // optional uint64 match_id = 1;
  [[nodiscard]] bool has_match_id()
      const;
  void clear_match_id() ;
  [[nodiscard]] ::uint64_t match_id() const;
  void set_match_id(::uint64_t value);

  private:
  ::uint64_t _internal_match_id() const;
  void _internal_set_match_id(::uint64_t value);

  public:
  // optional uint32 instance_id = 2;
  [[nodiscard]] bool has_instance_id()
      const;
  void clear_instance_id() ;
  [[nodiscard]] ::uint32_t instance_id() const;
  void set_instance_id(::uint32_t value);

  private:
  ::uint32_t _internal_instance_id() const;
  void _internal_set_instance_id(::uint32_t value);

  public:
  // optional uint32 signupfragment = 3;
  [[nodiscard]] bool has_signupfragment()
      const;
  void clear_signupfragment() ;
  [[nodiscard]] ::uint32_t signupfragment() const;
  void set_signupfragment(::uint32_t value);

  private:
  ::uint32_t _internal_signupfragment() const;
  void _internal_set_signupfragment(::uint32_t value);

  public:
  // optional uint32 currentfragment = 4;
  [[nodiscard]] bool has_currentfragment()
      const;
  void clear_currentfragment() ;
  [[nodiscard]] ::uint32_t currentfragment() const;
  void set_currentfragment(::uint32_t value);

  private:
  ::uint32_t _internal_currentfragment() const;
  void _internal_set_currentfragment(::uint32_t value);

  public:
  // optional float tickrate = 5;
  [[nodiscard]] bool has_tickrate()
      const;
  void clear_tickrate() ;
  [[nodiscard]] float tickrate() const;
  void set_tickrate(float value);

  private:
  float _internal_tickrate() const;
  void _internal_set_tickrate(float value);

  public:
  // optional uint32 tick = 6;
  [[nodiscard]] bool has_tick()
      const;
  void clear_tick() ;
  [[nodiscard]] ::uint32_t tick() const;
  void set_tick(::uint32_t value);

  private:
  ::uint32_t _internal_tick() const;
  void _internal_set_tick(::uint32_t value);

  public:
  // optional float rtdelay = 8;
  [[nodiscard]] bool has_rtdelay()
      const;
  void clear_rtdelay() ;
  [[nodiscard]] float rtdelay() const;
  void set_rtdelay(float value);

  private:
  float _internal_rtdelay() const;
  void _internal_set_rtdelay(float value);

  public:
  // optional float rcvage = 9;
  [[nodiscard]] bool has_rcvage()
      const;
  void clear_rcvage() ;
  [[nodiscard]] float rcvage() const;
  void set_rcvage(float value);

  private:
  float _internal_rcvage() const;
  void _internal_set_rcvage(float value);

  public:
  // optional float keyframe_interval = 10;
  [[nodiscard]] bool has_keyframe_interval()
      const;
  void clear_keyframe_interval() ;
  [[nodiscard]] float keyframe_interval() const;
  void set_keyframe_interval(float value);

  private:
  float _internal_keyframe_interval() const;
  void _internal_set_keyframe_interval(float value);

  public:
  // optional uint32 cdndelay = 11;
  [[nodiscard]] bool has_cdndelay()
      const;
  void clear_cdndelay() ;
  [[nodiscard]] ::uint32_t cdndelay() const;
  void set_cdndelay(::uint32_t value);

  private:
  ::uint32_t _internal_cdndelay() const;
  void _internal_set_cdndelay(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CEngineGotvSyncPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CEngineGotvSyncPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t match_id_;
    ::uint32_t instance_id_;
    ::uint32_t signupfragment_;
    ::uint32_t currentfragment_;
    float tickrate_;
    ::uint32_t tick_;
    float rtdelay_;
    float rcvage_;
    float keyframe_interval_;
    ::uint32_t cdndelay_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_engine_5fgcmessages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<22> CEngineGotvSyncPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CEngineGotvSyncPacket

// optional uint64 match_id = 1;
inline bool CEngineGotvSyncPacket::has_match_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_match_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t CEngineGotvSyncPacket::match_id() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.match_id)
  return _internal_match_id();
}
inline void CEngineGotvSyncPacket::set_match_id(::uint64_t value) {
  _internal_set_match_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.match_id)
}
inline ::uint64_t CEngineGotvSyncPacket::_internal_match_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.match_id_;
}
inline void CEngineGotvSyncPacket::_internal_set_match_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.match_id_ = value;
}

// optional uint32 instance_id = 2;
inline bool CEngineGotvSyncPacket::has_instance_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_instance_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.instance_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CEngineGotvSyncPacket::instance_id() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.instance_id)
  return _internal_instance_id();
}
inline void CEngineGotvSyncPacket::set_instance_id(::uint32_t value) {
  _internal_set_instance_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.instance_id)
}
inline ::uint32_t CEngineGotvSyncPacket::_internal_instance_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.instance_id_;
}
inline void CEngineGotvSyncPacket::_internal_set_instance_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.instance_id_ = value;
}

// optional uint32 signupfragment = 3;
inline bool CEngineGotvSyncPacket::has_signupfragment() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_signupfragment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signupfragment_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t CEngineGotvSyncPacket::signupfragment() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.signupfragment)
  return _internal_signupfragment();
}
inline void CEngineGotvSyncPacket::set_signupfragment(::uint32_t value) {
  _internal_set_signupfragment(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.signupfragment)
}
inline ::uint32_t CEngineGotvSyncPacket::_internal_signupfragment() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signupfragment_;
}
inline void CEngineGotvSyncPacket::_internal_set_signupfragment(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signupfragment_ = value;
}

// optional uint32 currentfragment = 4;
inline bool CEngineGotvSyncPacket::has_currentfragment() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_currentfragment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currentfragment_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t CEngineGotvSyncPacket::currentfragment() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.currentfragment)
  return _internal_currentfragment();
}
inline void CEngineGotvSyncPacket::set_currentfragment(::uint32_t value) {
  _internal_set_currentfragment(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.currentfragment)
}
inline ::uint32_t CEngineGotvSyncPacket::_internal_currentfragment() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.currentfragment_;
}
inline void CEngineGotvSyncPacket::_internal_set_currentfragment(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currentfragment_ = value;
}

// optional float tickrate = 5;
inline bool CEngineGotvSyncPacket::has_tickrate() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_tickrate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tickrate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline float CEngineGotvSyncPacket::tickrate() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.tickrate)
  return _internal_tickrate();
}
inline void CEngineGotvSyncPacket::set_tickrate(float value) {
  _internal_set_tickrate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.tickrate)
}
inline float CEngineGotvSyncPacket::_internal_tickrate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tickrate_;
}
inline void CEngineGotvSyncPacket::_internal_set_tickrate(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tickrate_ = value;
}

// optional uint32 tick = 6;
inline bool CEngineGotvSyncPacket::has_tick() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_tick() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tick_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t CEngineGotvSyncPacket::tick() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.tick)
  return _internal_tick();
}
inline void CEngineGotvSyncPacket::set_tick(::uint32_t value) {
  _internal_set_tick(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.tick)
}
inline ::uint32_t CEngineGotvSyncPacket::_internal_tick() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tick_;
}
inline void CEngineGotvSyncPacket::_internal_set_tick(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tick_ = value;
}

// optional float rtdelay = 8;
inline bool CEngineGotvSyncPacket::has_rtdelay() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_rtdelay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rtdelay_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline float CEngineGotvSyncPacket::rtdelay() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.rtdelay)
  return _internal_rtdelay();
}
inline void CEngineGotvSyncPacket::set_rtdelay(float value) {
  _internal_set_rtdelay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.rtdelay)
}
inline float CEngineGotvSyncPacket::_internal_rtdelay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rtdelay_;
}
inline void CEngineGotvSyncPacket::_internal_set_rtdelay(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rtdelay_ = value;
}

// optional float rcvage = 9;
inline bool CEngineGotvSyncPacket::has_rcvage() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_rcvage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rcvage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline float CEngineGotvSyncPacket::rcvage() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.rcvage)
  return _internal_rcvage();
}
inline void CEngineGotvSyncPacket::set_rcvage(float value) {
  _internal_set_rcvage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.rcvage)
}
inline float CEngineGotvSyncPacket::_internal_rcvage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rcvage_;
}
inline void CEngineGotvSyncPacket::_internal_set_rcvage(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rcvage_ = value;
}

// optional float keyframe_interval = 10;
inline bool CEngineGotvSyncPacket::has_keyframe_interval() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_keyframe_interval() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keyframe_interval_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline float CEngineGotvSyncPacket::keyframe_interval() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.keyframe_interval)
  return _internal_keyframe_interval();
}
inline void CEngineGotvSyncPacket::set_keyframe_interval(float value) {
  _internal_set_keyframe_interval(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.keyframe_interval)
}
inline float CEngineGotvSyncPacket::_internal_keyframe_interval() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keyframe_interval_;
}
inline void CEngineGotvSyncPacket::_internal_set_keyframe_interval(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keyframe_interval_ = value;
}

// optional uint32 cdndelay = 11;
inline bool CEngineGotvSyncPacket::has_cdndelay() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000200U);
  return value;
}
inline void CEngineGotvSyncPacket::clear_cdndelay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cdndelay_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint32_t CEngineGotvSyncPacket::cdndelay() const {
  // @@protoc_insertion_point(field_get:CEngineGotvSyncPacket.cdndelay)
  return _internal_cdndelay();
}
inline void CEngineGotvSyncPacket::set_cdndelay(::uint32_t value) {
  _internal_set_cdndelay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:CEngineGotvSyncPacket.cdndelay)
}
inline ::uint32_t CEngineGotvSyncPacket::_internal_cdndelay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cdndelay_;
}
inline void CEngineGotvSyncPacket::_internal_set_cdndelay(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cdndelay_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // engine_5fgcmessages_2eproto_2epb_2eh
